### ISSUE TITLE
can this model do image to video ?

### ISSUE THREAD

**Issue by huanggou666** [kijai/ComfyUI-CogVideoXWrapper#1]
It would be awesome

**Comment by shaoxiongduan** [comment]
yeah that would be so cool!

**Comment by strangePause** [comment]
+1. This would be fantastic

**Comment by kijai** [comment]
Nope, and the official answer they have given is that they won't open source the image2video model:

https://github.com/THUDM/CogVideo/issues/88#issuecomment-2273572339
