### ISSUE TITLE
Add to CogVideoX page

### ISSUE THREAD

**Issue by zRzRzRzRzRzRzR** [kijai/ComfyUI-CogVideoXWrapper#10]
I hope this message finds you well.

 We are truly delighted to see your valuable contributions to CogVideoX. I am one of the maintainers of the official CogVideoX repository, and I would like to inquire if you would be willing to be added to our official contributor list. We would also love to feature and promote your work in our community.

**Comment by kijai** [comment]
I'm sorry I completely missed this question, of course you can add (if you didn't already)!

**Comment by zRzRzRzRzRzRzR** [comment]
I will add it quickly, sorry about missing
