### ISSUE TITLE
Base model and the GGUF model differences?

### ISSUE THREAD

**Issue by hassakajin** [kijai/ComfyUI-CogVideoXWrapper#100]
What's the difference between a 5bFun model and the 5bfun-GGUF model? i get images more vivid and darker with GGUF versions, is that the only thing it's for? i am so confused about these model versions, is there a description for each somewhere?

**Comment by kijai** [comment]
GGUF is just different way to optimize the model by quantization, results are a bit different, but main thing is that it uses less VRAM, and is slightly slower.

**Comment by hassakajin** [comment]
well that's interesting, thanks for the reply!
