### ISSUE TITLE
'list' object has no attribute 'to'

### ISSUE THREAD

**Issue by XieJunchen** [kijai/ComfyUI-CogVideoXWrapper#11]
The project has been updated, the ksampler needs two input (plus or minus), maybe it needs to run the clip model?

**Comment by crazier9527** [comment]
Don't use the default clip text encoder, there is a CogVideo Text Encoder node.

look this:  https://github.com/kijai/ComfyUI-CogVideoXWrapper/issues/19#issuecomment-2313915458
