### ISSUE TITLE
module 'torch' has no attribute 'float8_e4m3fn'

### ISSUE THREAD

**Issue by wangqun888** [kijai/ComfyUI-CogVideoXWrapper#12]
使用代码中工作流，运行报错如下：module 'torch' has no attribute 'float8_e4m3fn'。
不知道这是什么原因造成的。

**Comment by wangqun888** [comment]
<img width="1417" alt="image" src="https://github.com/user-attachments/assets/9a45f6e3-4207-4ed3-87dd-ac018f0f526b">
追加图片

**Comment by kijai** [comment]
Torch version is too old.
