### ISSUE TITLE
CogVideoX-Fun-V1.1-5b-InP -> Sizes of tensors must match except in dimension 2. Expected size 480 but got size 576 for tensor number 1 in the list.

### ISSUE THREAD

**Issue by tdtrumble** [kijai/ComfyUI-CogVideoXWrapper#120]
Tried to load up the new CogVideoX-Fun-V1.1-5b-InP into CogVideoXFun Sample and got : Sizes of tensors must match except in dimension 2. Expected size 480 but got size 576 for tensor number 1 in the list.

The 480 was constant but the 576 varies based on how I set the Base Resolution. Did some quick math and to get it to equal 480 I needed value to be 640, so I altered nodes.py with the below and it worked. Not sure if pull request is needed to update list to add 640 or if I did something wrong with the existing nodes?

class CogVideoXFunSampler:
    @classmethod
    def INPUT_TYPES(s):
        return {
            "required": {
                "pipeline": ("COGVIDEOPIPE",),
                "positive": ("CONDITIONING", ),
                "negative": ("CONDITIONING", ),
                "video_length": ("INT", {"default": 49, "min": 5, "max": 49, "step": 4}),
                "base_resolution": (
                    [ 
                        256,
                        320,
                        384,
                        448,
                        512,
						640,  <-----------
                        768,
                        960,
                        1024,
                    ], {"default": 768}
                ),

**Comment by K-Max-Me** [comment]
Can confirm this fixed my issue too. I thought this model can accept varied resolutions.
