### ISSUE TITLE
i don't know where the problem is.

### ISSUE THREAD

**Issue by K-O-N-B** [kijai/ComfyUI-CogVideoXWrapper#124]
![image](https://github.com/user-attachments/assets/1ca3e9d2-122f-4147-90da-d9bf469bbe36)

![image](https://github.com/user-attachments/assets/4e13c0d3-162d-42e2-a404-c00990331297)

**Comment by K-O-N-B** [comment]
![image](https://github.com/user-attachments/assets/d3a77ee3-f3ba-4777-a2f8-4fd3922f45dd)

**Comment by kijai** [comment]
The I2V model does not support portrait mode, or anything besides 720x480.

You can use the CogVideoX-Fun version instead, it supports a lot more resolutions and frame counts.

**Comment by K-O-N-B** [comment]
i see...
