### ISSUE TITLE
onediff support

### ISSUE THREAD

**Issue by hassakajin** [kijai/ComfyUI-CogVideoXWrapper#126]
Is onediff supported in Comfy portable + windows? i haven't found any useful tutorial on how to install it properly, or what platform is it compatible with, i've seen old reddit posts showing the performance improvements, but no guide on how to do it.

That's my last issue for a while, i do want that 40% speed increase if it's possible :/

**Comment by kijai** [comment]
Onediff itself is not supported in Windows.

**Comment by hassakajin** [comment]
Oh man this is sad,  i thought it was. 
Big Thanks though!
