### ISSUE TITLE
No module named 'onediffx'

### ISSUE THREAD

**Issue by wuliang19869312** [kijai/ComfyUI-CogVideoXWrapper#127]
May I ask what is the problem with this, when compile opens and selects onediffx it reports an error

**Comment by kijai** [comment]
You don't have onediffx installed. It is only supported on Linux and for installing it you should refer to their instructions:

https://github.com/siliconflow/onediff

**Comment by wuliang19869312** [comment]
│ exit code: 1
╰─> [7 lines of output]
Traceback (most recent call last):
File "", line 2, in
File "", line 34, in
File "E:\ComfyUI\custom_nodes\onediff\setup.py", line 37, in
long_description=open("README.md").read(),
^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 5663: illegal multibyte sequence
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


Hmm, I've tried installing it, but it always reports an error~~ Is there any trick to this installation?

**Comment by kijai** [comment]
It can not be installed on Windows.
