### ISSUE TITLE
Save the model file to another location

### ISSUE THREAD

**Issue by toyxyz** [kijai/ComfyUI-CogVideoXWrapper#131]
Thanks for the great work as always!

The Cogvideo model is too large and I want to move it to HDD instead of SSD, is it possible to download or save the model file in a different path? Modifying the extra_model_paths.yaml didn't work.

**Comment by cheezecrisp** [comment]
mklink(for windows) / ln(for linux) will help

**Comment by pondloso** [comment]
For me it take forever to load  Cog model if it not on ssd.
my ssd always had like 10-20 gb left i need to move in model in and out to swap instead.

**Comment by kijai** [comment]
I usually just symlink, but yeah would be good to have it in extra_model_paths too, I think it should work now, this worked after my latest update (excuse the inconsistent folder naming, don't really want to change it at this point):
![image](https://github.com/user-attachments/assets/9650c9aa-fdf1-425b-b315-ae4beafc69d0)
