### ISSUE TITLE
Can you create new example workflows for the newest features?

### ISSUE THREAD

**Issue by FemBoxbrawl** [kijai/ComfyUI-CogVideoXWrapper#134]
(if they work)

I am just kind of confused on how the lora stuff works, etc. where can I get new loras?

**Comment by kijai** [comment]
There's not many LoRAs available yet, it's mostly for testing at this point. Some can be found on huggingface, such as this that I used to test the loading: https://huggingface.co/a-r-r-o-w/cogvideox-disney-adamw-3000-0.0003

For the pose control there is an example workflow, which defaults to using dwpose, but that can be replaced with any kind of input.

Same for context windowing, there's simplest example workflow. Also very new feature so I don't know the best way to use it with CogVideoX yet myself.
