### ISSUE TITLE
some prompts can't be identified in several prompts together

### ISSUE THREAD

**Issue by yli6hz** [kijai/ComfyUI-CogVideoXWrapper#137]
When I input three prompts but animation only identifies two of them through img to video. For example, I input below prompts:
"The girl's hair is blown by the wind, blinks and turns her head slowly. Golden sparks exploded in the background and foreground“
The animation shows hair is blowing and sparks moving, but girl's eye and head is motionless. I tried several times and different pictures but result is same. I find only two of three could be identified. I don't know why it happens. Seed change is same.

**Comment by yli6hz** [comment]
![CogVideoX_Fun+RIFE+Upscaled_00006](https://github.com/user-attachments/assets/6dd2d497-2864-4a50-bfd8-9fd80cb07303)
This is my workflow via picture which could load into comfyUI.

**Comment by kijai** [comment]
Not really something I can do anything about, it's about the model itself.
