### ISSUE TITLE
torch.cat(): expected a non-empty list of Tensors

### ISSUE THREAD

**Issue by darthjawn** [kijai/ComfyUI-CogVideoXWrapper#14]
Repeatedly getting this error after using all example workflows and installation instructions.  Any ideas?

**Comment by adamjen** [comment]
I have the same error too

**Comment by haisheng666** [comment]
Please ask the open-source author to solve the problem. Thank you

**Comment by haisheng666** [comment]
What kind of garbage author and open source project closed without solving the problem?
