### ISSUE TITLE
Cogvideox cannot generate videos smaller than 6s, otherwise the video will be damaged

### ISSUE THREAD

**Issue by pyoliu** [kijai/ComfyUI-CogVideoXWrapper#140]
Cogvideox cannot generate videos smaller than 6s, otherwise the video will be damaged
![Uploading 微信图片_20241008165142.png…]()

**Comment by pyoliu** [comment]
![Uploading 微信图片_20241008165142.png…]()

**Comment by pyoliu** [comment]
![e7cd07d08fe5b0d7eeea69c326c3b11](https://github.com/user-attachments/assets/189127c8-b47a-4e1a-a950-d955262573ef)

**Comment by kijai** [comment]
Yes that's the limitation of that exact I2V model, nothing I can do about it. If you need different frame counts, you can use the "Fun" version instead.
