### ISSUE TITLE
`prompt_embeds` and `negative_prompt_embeds` must have the same shape when passed directly, but got: `prompt_embeds` torch.Size([1, 226, 4096]) != `negative_prompt_embeds` torch.Size([1, 452, 4096]).

### ISSUE THREAD

**Issue by hexe63** [kijai/ComfyUI-CogVideoXWrapper#144]
Fehler tritt auf wenn "Negativ Prompt" leer ist.

**Comment by hexe63** [comment]
File "...ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "...ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "...ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "...ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "...ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 1078, in process
    latents = pipe(
  File "...ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "...ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\cogvideox_fun\pipeline_cogvideox_inpaint.py", line 703, in __call__
    self.check_inputs(
  File "...ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\cogvideox_fun\pipeline_cogvideox_inpaint.py", line 492, in check_inputs
    raise ValueError(
ValueError: `prompt_embeds` and `negative_prompt_embeds` must have the same shape when passed directly, but got: `prompt_embeds` torch.Size([1, 226, 4096]) != `negative_prompt_embeds` torch.Size([1, 452, 4096]).

**Comment by kijai** [comment]
Negative prompt is too long.

**Comment by hexe63** [comment]
Sorry,
Negative prompt is "Empty", then how can it be too long?

**Comment by kijai** [comment]
The error says so, what workflow is this?

**Comment by hexe63** [comment]
Ok, here is the simplified workflow as a raw file
[Simple Cog workflow.json](https://github.com/user-attachments/files/17318148/Simple.Cog.workflow.json)

**Comment by kijai** [comment]
> Ok, here is the simplified workflow as a raw file [Simple Cog workflow.json](https://github.com/user-attachments/files/17318148/Simple.Cog.workflow.json)

I don't know what that text box node does, but it must be what's causing the issue. Easy to check by trying me example workflows that are included in the examples -folder.

**Comment by hexe63** [comment]
Okay, thanks for the feedback. 

The workflow is part of a larger workflow, here the positive and negative prompts come from "IF_AI_Chat Prompt" with Ollama connection. Also for testing to be able to understand the number of tokens.
However,
I made the same entries in the corresponding example "cogvidex_fun_5b_GGUF_10GB_VRAM_example_01.json", the error is the same.
Here is the complete error message:

"Closest bucket size: 512x512
!!! Exception during processing !!! `prompt_embeds` and `negative_prompt_embeds` must have the same shape when passed directly, but got: `prompt_embeds` torch.Size([1, 452, 4096]) != `negative_prompt_embeds` torch.Size([1, 226, 4096]).
Traceback (most recent call last):
  File "...\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "...\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "...\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "...\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "...\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 1126, in process
    latents = pipe(
  File "...\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "...\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\cogvideox_fun\pipeline_cogvideox_inpaint.py", line 703, in __call__
    self.check_inputs(
  File "...\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\cogvideox_fun\pipeline_cogvideox_inpaint.py", line 492, in check_inputs
    raise ValueError(
ValueError: `prompt_embeds` and `negative_prompt_embeds` must have the same shape when passed directly, but got: `prompt_embeds` torch.Size([1, 452, 4096]) != `negative_prompt_embeds` torch.Size([1, 226, 4096]).

Prompt executed in 69.76 seconds"
[Simple_Cog_workflow_based_on_example_Workflow_cogvidex_fun_5b_GGUF_10GB_VRAM_example_01.json](https://github.com/user-attachments/files/17323392/Simple_Cog_workflow_based_on_example_Workflow_cogvidex_fun_5b_GGUF_10GB_VRAM_example_01.json)

Otherwise great work, keep it up!

**Comment by kijai** [comment]
> Okay, thanks for the feedback.
> 
> The workflow is part of a larger workflow, here the positive and negative prompts come from "IF_AI_Chat Prompt" with Ollama connection. Also for testing to be able to understand the number of tokens. However, I made the same entries in the corresponding example "cogvidex_fun_5b_GGUF_10GB_VRAM_example_01.json", the error is the same. Here is the complete error message:
> 
> "Closest bucket size: 512x512 !!! Exception during processing !!! `prompt_embeds` and `negative_prompt_embeds` must have the same shape when passed directly, but got: `prompt_embeds` torch.Size([1, 452, 4096]) != `negative_prompt_embeds` torch.Size([1, 226, 4096]). Traceback (most recent call last): File "...\ComfyUI\execution.py", line 323, in execute output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) File "...\ComfyUI\execution.py", line 198, in get_output_data return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) File "...\ComfyUI\execution.py", line 169, in _map_node_over_list process_inputs(input_dict, i) File "...\ComfyUI\execution.py", line 158, in process_inputs results.append(getattr(obj, func)(**inputs)) File "...\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 1126, in process latents = pipe( File "...\ComfyUI\venv\lib\site-packages\torch\utils_contextlib.py", line 116, in decorate_context return func(*args, **kwargs) File "...\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\cogvideox_fun\pipeline_cogvideox_inpaint.py", line 703, in **call** self.check_inputs( File "...\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\cogvideox_fun\pipeline_cogvideox_inpaint.py", line 492, in check_inputs raise ValueError( ValueError: `prompt_embeds` and `negative_prompt_embeds` must have the same shape when passed directly, but got: `prompt_embeds` torch.Size([1, 452, 4096]) != `negative_prompt_embeds` torch.Size([1, 226, 4096]).
> 
> Prompt executed in 69.76 seconds" [Simple_Cog_workflow_based_on_example_Workflow_cogvidex_fun_5b_GGUF_10GB_VRAM_example_01.json](https://github.com/user-attachments/files/17323392/Simple_Cog_workflow_based_on_example_Workflow_cogvidex_fun_5b_GGUF_10GB_VRAM_example_01.json)
> 
> Otherwise great work, keep it up!

Well in that one the positive prompt is too long.

**Comment by hexe63** [comment]
ok, yes the positive prompt is longer than 226 tokens.

What is this limitation for?

**Comment by kijai** [comment]
It's the max amount of tokens they trained it with, I don't know more.

**Comment by hexe63** [comment]
OK, thank you and keep it up
