### ISSUE TITLE
SageAttention on Windows

### ISSUE THREAD

**Issue by jpgallegoar** [kijai/ComfyUI-CogVideoXWrapper#150]
Using the help of the folks from [woct0rdho](https://github.com/woct0rdho/) I was able to get Triton and Sageattention running on windows. I got almost 25% drop in seconds per inference :). You can see this https://github.com/woct0rdho/triton/issues/3 for details.

Using bf16 + fp8 fastmode + sageattention I'm getting 4.25s/it at 50 steps and 16 chunk_size with 5B I2V model

**Comment by jpgallegoar** [comment]
> hello, what's Sageattention, is it torch compile or onediff?

https://github.com/thu-ml/SageAttention

It's a custom attention mechanism which uses triton (Inference optimization library created by OpenAI)

**Comment by WingeD123** [comment]
thanks for both reply, is sageattention works on all sampling or CogVideo only?

**Comment by WingeD123** [comment]
> > thanks for both reply, is sageattention works on all sampling or CogVideo only?
> 
> That I know, it works in Stable Diffusion, Flux and CogVideo because it has already been implemented by other people. But I think anything that uses Attention library can use SageAttention instead, just like Flash-Attention

only need pip install sageattention to make it working? didn't see speed differs on FLUX, trying cogvideo

**Comment by jpgallegoar** [comment]
> > > thanks for both reply, is sageattention works on all sampling or CogVideo only?
> > 
> > 
> > That I know, it works in Stable Diffusion, Flux and CogVideo because it has already been implemented by other people. But I think anything that uses Attention library can use SageAttention instead, just like Flash-Attention
> 
> only need pip install sageattention to make it working? didn't see speed differs on FLUX, trying cogvideo EDIT: cogvideo get about 30% speed boost :)

It was THAT easy for you?! It took me like 2 hours LMFAO. On FLUX you have to do something to get it running, search on google I only used it for CogVideoX. Congrats on the speed boost!

**Comment by WingeD123** [comment]
> > > > thanks for both reply, is sageattention works on all sampling or CogVideo only?
> > > 
> > > 
> > > That I know, it works in Stable Diffusion, Flux and CogVideo because it has already been implemented by other people. But I think anything that uses Attention library can use SageAttention instead, just like Flash-Attention
> > 
> > 
> > only need pip install sageattention to make it working? didn't see speed differs on FLUX, trying cogvideo EDIT: cogvideo get about 30% speed boost :)
> 
> It was THAT easy for you?! It took me like 2 hours LMFAO. On FLUX you have to do something to get it running, search on google I only used it for CogVideoX. Congrats on the speed boost!

i will double check the reason of cogvideo boost, maybe cause of triton?

**Comment by jpgallegoar** [comment]
Yeah SageAttention requires triton so you must have both already, otherwise pip install sageattention would have failed

**Comment by kijai** [comment]
Nice, I was meaning to test this but haven't had time yet, good to know the Windows Triton build also enables sageattn!

I haven't gotten any speed increase with Flux though, only CogVideoX so far.

On same topic, I was able to gain 15-20% with this when using fp16, not that useful as most run CogVideoX in fp8, but haven't tried with sageattn: https://github.com/aredden/torch-cublas-hgemm

**Comment by jpgallegoar** [comment]
> Nice, I was meaning to test this but haven't had time yet, good to know the Windows Triton build also enables sageattn!
> 
> I haven't gotten any speed increase with Flux though, only CogVideoX so far.
> 
> On same topic, I was able to gain 15-20% with this when using fp16, not that useful as most run CogVideoX in fp8, but haven't tried with sageattn: https://github.com/aredden/torch-cublas-hgemm

Awesome, they are not stackable, right?

**Comment by joeluo** [comment]
Thanks a lot. I installed SageAttention and Triton on Windows successfully.  Do I need to make other settings to make it work in ComfyUI?

**Comment by kijai** [comment]
> Thanks a lot. I installed SageAttention and Triton on Windows successfully. Do I need to make other settings to make it work in ComfyUI?

With CogVideoX using these nodes it's enabled automatically if it's available.

**Comment by kijai** [comment]
> > Nice, I was meaning to test this but haven't had time yet, good to know the Windows Triton build also enables sageattn!
> > I haven't gotten any speed increase with Flux though, only CogVideoX so far.
> > On same topic, I was able to gain 15-20% with this when using fp16, not that useful as most run CogVideoX in fp8, but haven't tried with sageattn: https://github.com/aredden/torch-cublas-hgemm
> 
> Awesome, they are not stackable, right?

They are actually, but CublasLinear is only for fp16 so it's not stackable with the fp8 fast mode.
