### ISSUE TITLE
Are loras supported for 5b-i2v?

### ISSUE THREAD

**Issue by TheRohitSharma** [kijai/ComfyUI-CogVideoXWrapper#151]
Hey, wondering if there is lora support for 5b-i2V? I can't figure out where to connect the CogVideo LoraSelect to (I don't see any lora inputs on the sampler node).  Wanting to test out https://huggingface.co/ECNU-CILab/ExVideo-CogVideoX-LoRA-129f-v1.

**Comment by kijai** [comment]
The LoRA input is to the model loader node.

**Comment by TheRohitSharma** [comment]
You're right. 🤦🏽‍♂️ My mistake. Thanks!

**Comment by sl33pyC01E** [comment]
How are you testing it out? I keep getting "max frames for image to video 49" "image to video can't go above 49 if context options none" "image to video does not currently support context condition"
