### ISSUE TITLE
having issue i don't know why

### ISSUE THREAD

**Issue by RYG81** [kijai/ComfyUI-CogVideoXWrapper#153]
![image](https://github.com/user-attachments/assets/73e195e9-c5b4-4fb6-beee-e35a2cce9ff5)
got this issue today after updating.
earlier it was working fine.

**Comment by kijai** [comment]
Full error? Workflow? Update from how long ago?

Most likely just some of the changes in the node inputs, try remaking the sampler node.

**Comment by kijai** [comment]
That workflow runs fine for me, maybe you haven't updated the nodes, or the update has failed?

**Comment by RYG81** [comment]
For me, I get same error, only thing that's new is I have installed sageattention and triton

**Comment by kijai** [comment]
What is the full error?

**Comment by RYG81** [comment]
[Full error.txt](https://github.com/user-attachments/files/17392862/Full.error.txt)
Here I have attached full error.

**Comment by kijai** [comment]
It's indeed error with Triton and nothing to do with these nodes:

![image](https://github.com/user-attachments/assets/10cfea60-89f9-4645-80f9-b894d4e23cd7)

**Comment by RYG81** [comment]
OK so removing triton should make things work? Any other suggestion to improve speed because I installed it expecting some speed boost.

**Comment by kijai** [comment]
> OK so removing triton should make things work? Any other suggestion to improve speed because I installed it expecting some speed boost.

I just tested it myself in Windows and got it working, so it definitely can work. I can't really offer support in installing all that as it's many steps with lots of things that can go wrong, I can only confirm it is possible.

Other than that: 
- fp8 fast mode obviously if supported by your system
- for image2vid, use less steps, it can work with surprisingly little, some samplers like SASolver perform better at low steps 
- if your VRAM allows, use PAB (just connect PAB config node to model loader)
- don't use GGUF unless you have to (VRAM, it's slower
- use smaller resolution, 5b fun version can do extremely small videos coherently that then could be upscaled by other means

**Comment by RYG81** [comment]
For now, I have removed Triton and sageattention just to make things work. May be in near future will spend time investigate how to make it work easily.
Thanks for helping out.

**Comment by RYG81** [comment]
After connecting to the person who build wheels for Triton I manage to make it work, however fp8 gives error-
torch._scaled_mm is only supported on CUDA devices with compute capability >= 9.0 or 8.9, or ROCm MI300+

**Comment by RYG81** [comment]
Also I am trying your suggestion, so if in example we got workflow with those things it will very helpful.
@jepjoo  At home I got RTX 4070 and here fp8 working fine, thanks for the reply.

**Comment by kijai** [comment]
> > After connecting to the person who build wheels for Triton I manage to make it work, however fp8 gives error- torch._scaled_mm is only supported on CUDA devices with compute capability >= 9.0 or 8.9, or ROCm MI300+
> > Just reopen to see if its possible to make fp8 also work.
> 
> I think that basically means Hopper and Ada Lovelace (RTX 40) only. You said you have 3060, I don't think it's supported for native fp8.
> 
> btw @kijai can you confirm whether Sageattention is also working on Windows? I have it + Triton installed but not sure how to tell whether it is being utilized or not.
> 
> Getting somewhere around 4.2s/it with CogVideo I2V 5B on a 4090, fp8 "fastmode" selected.

Yeah sageattn works if you can get Triton to work, that speed would suggest it's working, it's not quite as fast as on Linux, but still way faster than without.

**Comment by kijai** [comment]
> Also I am trying your suggestion, so if in example we got workflow with those things it will very helpful. @jepjoo At home I got RTX 4070 and here fp8 working fine, thanks for the reply.

Fp8 itself will work on 4070, but fp8_fastmode will not, that requires 4090 or newer GPU.
