### ISSUE TITLE
about exvideo+cogvideox

### ISSUE THREAD

**Issue by coollofty** [kijai/ComfyUI-CogVideoXWrapper#154]
https://huggingface.co/ECNU-CILab/ExVideo-CogVideoX-LoRA-129f-v1

I have discovered this and it seems to improve and stabilize the effectiveness of Cogvideox. Can be supported?

**Comment by kijai** [comment]
> https://huggingface.co/ECNU-CILab/ExVideo-CogVideoX-LoRA-129f-v1
> 
> I have discovered this and it seems to improve and stabilize the effectiveness of Cogvideox. Can be supported?

It is already supported, you just load it as LoRA:

![image](https://github.com/user-attachments/assets/80198cad-7f22-4dd8-aff6-774d61feaef4)

**Comment by coollofty** [comment]
Yes， This is great ! ^_^
