### ISSUE TITLE
ComfyUI-GGUF compatibility

### ISSUE THREAD

**Issue by unclemusclez** [kijai/ComfyUI-CogVideoXWrapper#155]
Are the CogVideoX tools compatible with: https://github.com/city96/ComfyUI-GGUF?

I am trying to load the quantized versions of the clips without much success, but it seems they would help with the VRAM usage.

**Comment by kijai** [comment]
It's not compatible, but also it would not affect the VRAM usage during sampling and would only be helpful if you can't get past the text encoding stage.
