### ISSUE TITLE
"Max 49 frames" but ECNU-CILab/ExVideo-CogVideoX-LoRA-129f-v1

### ISSUE THREAD

**Issue by sl33pyC01E** [kijai/ComfyUI-CogVideoXWrapper#156]
I see a lot of reference to this lora in closed issues but I have been unable to get it to work in my environment due to behaviors of the custom nodes.

Am I missing something obvious?

**Comment by kijai** [comment]
> I see a lot of reference to this lora in closed issues but I have been unable to get it to work in my environment due to behaviors of the custom nodes.
> 
> Am I missing something obvious?

It's a LoRa for the text2video, not image2video.

**Comment by sl33pyC01E** [comment]
i was able to resolve the error readout by recreating the nodes 😅

you are also correct I believe
