### ISSUE TITLE
missing nodes

### ISSUE THREAD

**Issue by 4lt3r3go** [kijai/ComfyUI-CogVideoXWrapper#157]
https://github.com/kijai/ComfyUI-CogVideoXWrapper/blob/main/examples/cogvideox_interpolation_example_01.json

the workflow here show a missing node.
where i can take this?

**Comment by kijai** [comment]
Gonna need more information than that...

**Comment by 4lt3r3go** [comment]
> Gonna need more information than that...

![image](https://github.com/user-attachments/assets/edaac0c5-547b-4b63-add5-b3f51d45b2e1)

**Comment by kijai** [comment]
> > Gonna need more information than that...
> 
> ![image](https://github.com/user-attachments/assets/edaac0c5-547b-4b63-add5-b3f51d45b2e1)
> 

You have not updated the nodes.

**Comment by 4lt3r3go** [comment]
i had. 
did update today again and magically now works. misteries of comfyUI.
thnks
