### ISSUE TITLE
Is there any chance of having a Gguf 'CogVideoX-Interpolation -model'?

### ISSUE THREAD

**Issue by jav12z** [kijai/ComfyUI-CogVideoXWrapper#158]
Please, please, please

Many thanks for your amazing work.

**Comment by kijai** [comment]
This is done.

**Comment by jav12z** [comment]
Many thanks!!!

https://github.com/user-attachments/assets/30ad9351-2012-498e-adab-56a71008f545

For my first test, I tried something a bit extreme, didn't obtain what I was expecting but I found very interesting the transition.

Thanks again.
