### ISSUE TITLE
an error was shown on nonetype

### ISSUE THREAD

**Issue by Mistermango23** [kijai/ComfyUI-CogVideoXWrapper#168]
![info7](https://github.com/user-attachments/assets/5db5354d-e8a6-40cb-8f49-9c3bf0f76459)

can you fix this? i can't do ai video generation.

**Comment by Mistermango23** [comment]
it was from VHS

**Comment by Mistermango23** [comment]
@kijai

**Comment by kijai** [comment]
It's a VHS error so no idea, try the usual: update VHS nodes and remake the video combine node. Also try just any other node like image preview to see if the issue is the VHS node.

**Comment by Mistermango23** [comment]
I've already done that! This shows again.. @kijai

**Comment by kijai** [comment]
Show the whole error

**Comment by Mistermango23** [comment]
Look! @kijai 

![error6](https://github.com/user-attachments/assets/78c4e06c-608d-46f5-9907-8084fd37e25d)
![error4](https://github.com/user-attachments/assets/81733807-5b85-4768-9247-096eeb94ca6f)

Code error:
got prompt
Failed to validate prompt for output 44:
* (prompt):
  - Exception when validating node: 'NoneType' object is not callable
* VHS_VideoCombine 44:
  - Exception when validating node: 'NoneType' object is not callable
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': "Exception when validating node: 'NoneType' object is not callable", 'extra_info': {}}

**Comment by kijai** [comment]
That is still not the whole error, did you try using some other output node and see if they show something? For example:

![image](https://github.com/user-attachments/assets/b04e38b0-f9a4-42e8-9c27-fa37a6f1bed7)

**Comment by Mistermango23** [comment]
???
https://www.youtube.com/watch?v=t2Fp32UlpuI

**Comment by AustinMroz** [comment]
It's not an issue I've been able to reproduce. I think the odds of Kijai's wrapper being in any way involved are incredibly slim, but the previous [report I received for this](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/discussions/280) did not a provide a full view of the workflow to confirm.

The VALIDATE_NODES used for Video Combine is trivial, but from my digging:
- The function definition used by Video Combine is non-standard. It includes kwargs for backwards compatibility with very old versions of comfy, but kwargs now has explicit meaning post execution inversion.
- The code contained in the try/except block is broad and is swallowing the actual callstack where the error occurs
  - Getting a proper error stack would require changing the final line of the offending except block in execution.py from a continue to a raise. More than I would want to drag a person into.
- The try block is calling into other user code. I can produce a log with `Exception when validating node:` by raising an exception in INPUT_TYPES
- What little information there is to gleam from the error message (A variable set to None being called) leaves me scratching my head. I can't think of a place in VHS code where this could occur.

**Comment by kirkware** [comment]
disabling ComfyUI_ezXY resolved this issue for me
