### ISSUE TITLE
FP8e4m3 precision for CogVideoX-5B model?

### ISSUE THREAD

**Issue by jepjoo** [kijai/ComfyUI-CogVideoXWrapper#17]
Apparently the new 5B model supports FP8 inference and ComfyUI supports native 8-bit inference for Ada/RTX 40 GPU's when using FP8e4m3. It might be quite a bit faster than BF16 with those cards, so would be cool to have that as an option.

![Screenshot 2024-08-27 at 18-08-24 kh8udvlyg7ld1 jpg (WEBP Image 2570 × 2256 pixels)](https://github.com/user-attachments/assets/9b2cf539-f0d2-4758-b8bb-d133966a6523)

**Comment by kijai** [comment]
The pipeline didn't support that at all, I hacked it in to best of my knowledge and it does drop memory use by ~5GB. Not any faster though as diffusers doesn't support the optimized fp8 stuff currently.
