### ISSUE TITLE
Spline behavior

### ISSUE THREAD

**Issue by hassakajin** [kijai/ComfyUI-CogVideoXWrapper#172]
is this normal for the spline output to be increasing in size? in the [example](https://private-user-images.githubusercontent.com/40791699/378229701-d5334237-03dc-48f5-8bec-3ae5998660c6.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTE2NzUsIm5iZiI6MTcyOTY5MTM3NSwicGF0aCI6Ii80MDc5MTY5OS8zNzgyMjk3MDEtZDUzMzQyMzctMDNkYy00OGY1LThiZWMtM2FlNTk5ODY2MGM2Lm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDEzNDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ZjE2MWQxMmYyOTExZDc2OTQ3YTg3MjZhMWI4MWU4Y2Y0NmFjMWUxNzUxNjgwNTc1ZGZlZjA0NWRmZTNhZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WC9zTNUOJfGuFVjlCshTfozqZhPfR2bk1oliQLpHtXU) it's a perfect circle from start to end, but on my end it gradually gets really big, is it normal? 
![brave_screenshot](https://github.com/user-attachments/assets/d2155ad7-6556-4c7e-bc2a-d95144167f56)
![brave_screenshot (1)](https://github.com/user-attachments/assets/211b1282-6383-4d17-b054-df52e23e4e7f)

**Comment by kijai** [comment]
It was a bug in the shape create code, I fixed it couple of days ago, updating KJNodes should fix that for you.

**Comment by hassakajin** [comment]
> It was a bug in the shape create code, I fixed it couple of days ago, updating KJNodes should fix that for you.

Oh sweet. Thanks again Kijai! It's fixed now, i don't usually update nodes unless something really breaks it xD
By the way Tora been super fun to play with, just incredible where this is going, thanks for bringing it so fast.
