### ISSUE TITLE
Can I use two splines? 

### ISSUE THREAD

**Issue by joeluo** [kijai/ComfyUI-CogVideoXWrapper#173]
I saw in the example that two cats can correspond to two splines, but I can't find where to add the second one.
Thanks a lot.

**Comment by kijai** [comment]
Yeah it's a bit clumsy for now, I added a node to append the coordinates and updated the Tora nodes to accept list of coordinate strings, like so:

![image](https://github.com/user-attachments/assets/25be13c6-bd84-4732-9185-f66f5dd9d2c9)

**Comment by joeluo** [comment]
I updated it, but I can't see 'Append Strings To List', and the Spline Editor doesn't have an input either.

**Comment by kijai** [comment]
> I updated it, but I can't see 'Append Strings To List', and the Spline Editor doesn't have an input either.

KJNodes, not these nodes, doesn't sound like it did get updated as both of those things are in current version.

**Comment by joeluo** [comment]
Tks a lot, after updated KJNodes, they appeared.
