### ISSUE TITLE
How to add 2 trajectory lines in the curve editor？

### ISSUE THREAD

**Issue by zergqyue** [kijai/ComfyUI-CogVideoXWrapper#176]
I saw that there are 2 trajectories in the official demo, but I don’t know how to draw them?

**Comment by hacknullchainik** [comment]
same question

**Comment by kijai** [comment]
I still need to add an example for that, basically you just append multiple spline editors:

![image](https://github.com/user-attachments/assets/e2093284-18f7-43bd-8eff-97bc5fcf774b)

**Comment by hacknullchainik** [comment]
thanks

**Comment by Gyramuur** [comment]
> I still need to add an example for that, basically you just append multiple spline editors:
> 
> ![image](https://private-user-images.githubusercontent.com/40791699/379768115-e2093284-18f7-43bd-8eff-97bc5fcf774b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MTQ0NDQsIm5iZiI6MTcyOTkxNDE0NCwicGF0aCI6Ii80MDc5MTY5OS8zNzk3NjgxMTUtZTIwOTMyODQtMThmNy00M2JkLThlZmYtOTdiYzVmY2Y3NzRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDAzNDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZDc4YjE4ZTk2MDBmZDA3MWNjYTBmMTAwZWUxNjFjZTc4YzI0MGFjYzE1MWVhOTAzNDM4NWUzYWU3MzYyYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lgg8_TA9fVOs9-XXTRA5bEmoOKRcdzjEHSeKjyDSPMI)

Bit unrelated, but how are you getting the image inside the spline editor? All I'm seeing is a blank grid and I have to guess where I am placing the path. Also my red dot seems to move toward the camera and get bigger over time for some reason?

**Comment by joeluo** [comment]
I made a  tutorial for this, but it is chinese. I hope you can understand. https://youtu.be/-gxlCAe9HzA

**Comment by kijai** [comment]
> > I still need to add an example for that, basically you just append multiple spline editors:
> > ![image](https://private-user-images.githubusercontent.com/40791699/379768115-e2093284-18f7-43bd-8eff-97bc5fcf774b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MTQ0NDQsIm5iZiI6MTcyOTkxNDE0NCwicGF0aCI6Ii80MDc5MTY5OS8zNzk3NjgxMTUtZTIwOTMyODQtMThmNy00M2JkLThlZmYtOTdiYzVmY2Y3NzRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDAzNDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZDc4YjE4ZTk2MDBmZDA3MWNjYTBmMTAwZWUxNjFjZTc4YzI0MGFjYzE1MWVhOTAzNDM4NWUzYWU3MzYyYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lgg8_TA9fVOs9-XXTRA5bEmoOKRcdzjEHSeKjyDSPMI)
> 
> Bit unrelated, but how are you getting the image inside the spline editor? All I'm seeing is a blank grid and I have to guess where I am placing the path. Also my red dot seems to move toward the camera and get bigger over time for some reason?

Make sure KJNodes is up to date, and you can just select the node and paste in image with copy/paste, or drag and drop an image in. In the update I made few days ago I also added image input into the node, which grabs it when the workflow is run to that point, it's a bit clumsy to use because of that requirement, but workable if you for example mute the other nodes or just the last output node first, or cancel the run once the editor gets the image.

**Comment by Gyramuur** [comment]
> > > I still need to add an example for that, basically you just append multiple spline editors:
> > > ![image](https://private-user-images.githubusercontent.com/40791699/379768115-e2093284-18f7-43bd-8eff-97bc5fcf774b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MTQ0NDQsIm5iZiI6MTcyOTkxNDE0NCwicGF0aCI6Ii80MDc5MTY5OS8zNzk3NjgxMTUtZTIwOTMyODQtMThmNy00M2JkLThlZmYtOTdiYzVmY2Y3NzRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDAzNDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZDc4YjE4ZTk2MDBmZDA3MWNjYTBmMTAwZWUxNjFjZTc4YzI0MGFjYzE1MWVhOTAzNDM4NWUzYWU3MzYyYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lgg8_TA9fVOs9-XXTRA5bEmoOKRcdzjEHSeKjyDSPMI)
> > 
> > 
> > Bit unrelated, but how are you getting the image inside the spline editor? All I'm seeing is a blank grid and I have to guess where I am placing the path. Also my red dot seems to move toward the camera and get bigger over time for some reason?
> 
> Make sure KJNodes is up to date, and you can just select the node and paste in image with copy/paste, or drag and drop an image in. In the update I made few days ago I also added image input into the node, which grabs it when the workflow is run to that point, it's a bit clumsy to use because of that requirement, but workable if you for example mute the other nodes or just the last output node first, or cancel the run once the editor gets the image.

Thanks for the help :) and the dot growing? Or does the size of the dot not affect anything?

**Comment by kijai** [comment]
> > > > I still need to add an example for that, basically you just append multiple spline editors:
> > > > ![image](https://private-user-images.githubusercontent.com/40791699/379768115-e2093284-18f7-43bd-8eff-97bc5fcf774b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MTQ0NDQsIm5iZiI6MTcyOTkxNDE0NCwicGF0aCI6Ii80MDc5MTY5OS8zNzk3NjgxMTUtZTIwOTMyODQtMThmNy00M2JkLThlZmYtOTdiYzVmY2Y3NzRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDAzNDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZDc4YjE4ZTk2MDBmZDA3MWNjYTBmMTAwZWUxNjFjZTc4YzI0MGFjYzE1MWVhOTAzNDM4NWUzYWU3MzYyYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lgg8_TA9fVOs9-XXTRA5bEmoOKRcdzjEHSeKjyDSPMI)
> > > 
> > > 
> > > Bit unrelated, but how are you getting the image inside the spline editor? All I'm seeing is a blank grid and I have to guess where I am placing the path. Also my red dot seems to move toward the camera and get bigger over time for some reason?
> > 
> > Make sure KJNodes is up to date, and you can just select the node and paste in image with copy/paste, or drag and drop an image in. In the update I made few days ago I also added image input into the node, which grabs it when the workflow is run to that point, it's a bit clumsy to use because of that requirement, but workable if you for example mute the other nodes or just the last output node first, or cancel the run once the editor gets the image.
> 
> Thanks for the help :) and the dot growing? Or does the size of the dot not affect anything?

The growing should have been fixed week ago too, it was a bug when the size_multiplier input was not used and it just grew by one each iteration.
