### ISSUE TITLE
tora problem

### ISSUE THREAD

**Issue by zzddwyff** [kijai/ComfyUI-CogVideoXWrapper#179]
![20241025-115642](https://github.com/user-attachments/assets/536821f3-bce5-49d7-81b3-37b3d26045fd)
Error while deserializing header: MetadataIncompleteBuffer

maybe is the clip file,where is the t5\google_t5-v1_1-xxl_encoderonly-fp8_e4m3fn.safetensors
I can't find it

**Comment by zzddwyff** [comment]
I use
![image](https://github.com/user-attachments/assets/11b2718e-56b2-4386-b748-7ebc9a66ff72)
from the
![image](https://github.com/user-attachments/assets/3fc2ac92-e749-4f0d-924a-ee41e508b25e)

**Comment by kijai** [comment]
MetadataIncompleteBuffer usually means the file is corrupt.
