### ISSUE TITLE
Tora cann't not run

### ISSUE THREAD

**Issue by littleyeson** [kijai/ComfyUI-CogVideoXWrapper#184]
Cann't not run display this error.How to fixed it?Thx
![微信截图_20241025235442](https://github.com/user-attachments/assets/3ce3b599-5377-4e71-94fa-1e3643027aed)
![微信截图_20241026000535](https://github.com/user-attachments/assets/a9bfedc4-393b-45a1-90a3-2edc7f0aa502)

**Comment by littleyeson** [comment]
![微信截图_20241026024444](https://github.com/user-attachments/assets/2b01b6ea-ed42-4e22-bdff-b0880b9cd1e0)

**Comment by kijai** [comment]
> ![微信截图_20241026024444](https://private-user-images.githubusercontent.com/70052345/380288822-2b01b6ea-ed42-4e22-bdff-b0880b9cd1e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4ODI3MDcsIm5iZiI6MTcyOTg4MjQwNywicGF0aCI6Ii83MDA1MjM0NS8zODAyODg4MjItMmIwMWI2ZWEtZWQ0Mi00ZTIyLWJkZmYtYjA4ODBiOWNkMWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDE4NTMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZjJlMGRkOThhOTdmNzQxZThjNzU0OTJhOGVhMDRmNDlhOGQ5OTExYzFmMzIxZDgzYTNjZjRhM2U2ZTM1NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JRsZ2ZnMQh3vXnA21k-CjCRTxwBurUl1_agek9wBuAA)

This error would come from not using the I2V model with image input.

**Comment by littleyeson** [comment]
> This error would come from not using the I2V model with image input.

which model can use image input?

**Comment by littleyeson** [comment]
THUDM/CogVideoX-5b-I2V this mode can use image input?

**Comment by kijai** [comment]
> THUDM/CogVideoX-5b-I2V this mode can use image input?

With Tora, that and the interpolation model, which has it's own example workflow too.
