### ISSUE TITLE
Does Tora work with 5B-I2V model? 

### ISSUE THREAD

**Issue by hacknullchainik** [kijai/ComfyUI-CogVideoXWrapper#185]
I did some test generations on my 3060 12 gb with i2v model and it seems like tora doesn't affect result much. Maybe im doing smth wrong? Can you share some settings for CogVideoX 5B I2V and Tora?

**Comment by kijai** [comment]
It does work, how well depends on the image. Some things move well and others don't. It's often even good idea to end it early by using low end_percent like 0.2

Some examples I've done:

https://github.com/user-attachments/assets/2f13ed4e-75ed-4c56-964f-11e53676dec6

https://github.com/user-attachments/assets/f9d1e812-081b-430c-9f6a-399d8c8c4dc7

**Comment by hacknullchainik** [comment]
Thanks, your examples look great, however i can't still get my image animated properly.
Maybe im running it with too low sampling steps or wrong scheduler?

**Comment by kijai** [comment]
I pretty much only have used the sampler and steps that are in the example testing workflow for this. It depends on the image, for example the above painting it never wanted to move the characters from their position, but controlling the hands was easy.

**Comment by hacknullchainik** [comment]
> it never wanted to move the characters from their position

lasy ass cog : (

**Comment by hacknullchainik** [comment]
thanks
