### ISSUE TITLE
Enable vae encode tiling for ToraEncode can dramatically reduce Vram occupied

### ISSUE THREAD

**Issue by tdrminglin** [kijai/ComfyUI-CogVideoXWrapper#190]
just copy the"Enable vae encode tiling " code  and insert it before  video_flow = vae.encode(video_flow)...

**Comment by shirubei** [comment]
Thank you!
I'm not familiar with the code at all.
Could you please point out where's the code for "Enable vae encode tiling " ?

**Comment by tdrminglin** [comment]
> Thank you! I'm not familiar with the code at all. Could you please point out where's the code for "Enable vae encode tiling " ?

        from .mz_enable_vae_encode_tiling import enable_vae_encode_tiling
        enable_vae_encode_tiling(vae)

**Comment by shirubei** [comment]
Awesome! 
You saved me.
Many thanks.

**Comment by junglehu** [comment]
I found the code video_flow = vae.encode(video_flow) at lines 447 and 515 in node.py. And I found the following code at line 246:

**Comment by kijai** [comment]
> I found the code video_flow = vae.encode(video_flow) at lines 447 and 515 in node.py. And I found the following code at line 246:
> 
> 
> if enable_tiling:
>     from .mz_enable_vae_encode_tiling import enable_vae_encode_tiling
>     enable_vae_encode_tiling(vae)
> 
> vae.to(device)
> 
> 
> How should I insert the code?

This is not necessary, the node has tiling option.

**Comment by junglehu** [comment]
> > Yes, there is an option for tiling in the node, and I have enabled it, but I still encounter an Out of Memory (OOM) error; the GPU is a 22GB 2080Ti.是的，节点中有一个平铺选项，并且我已启用它，但我仍然遇到内存不足（OOM）错误； GPU是22GB 2080Ti。
> > Tried to allocate 113.01 GiB尝试分配 113.01 GiB
> 
> How big of an image and how many images are you trying to encode exactly? Could be some specific issue with that GPU, the tiling works fine for me, and it's the same code discussed here anyway.您想要精确编码多大的图像以及多少图像？可能是该 GPU 的一些特定问题，平铺对我来说效果很好，而且无论如何，它与此处讨论的代码相同。

I attempted to generate a video of size 480x480 with 32 frames and 40 steps, but I still received an OOM error.
