### ISSUE TITLE
DownloadAndLoadCogVideoGGUFModel "RuntimeError: Windows not yet supported for torch.compile" but "compile" is disabled

### ISSUE THREAD

**Issue by Ratinod** [kijai/ComfyUI-CogVideoXWrapper#196]
![compile_bug](https://github.com/user-attachments/assets/38464f5d-d86f-4551-a261-8227e95e9bdf)

**Comment by kijai** [comment]
Oops, should be fixed now.

**Comment by Ratinod** [comment]
> Oops, should be fixed now.

That was fast. Thanks.

**Comment by kijai** [comment]
> > Oops, should be fixed now.
> 
> That was fast. Thanks.

Happened to be working on the code anyway!
