### ISSUE TITLE
How should I connect the Tora gguf node with the Tora encode Node?

### ISSUE THREAD

**Issue by jav12z** [kijai/ComfyUI-CogVideoXWrapper#197]
![image](https://github.com/user-attachments/assets/59d919a6-3620-4462-b0a0-7a1561ec1778)

The tora model is loaded as a cogvideopipe and not as Tora.

**Comment by kijai** [comment]
The Tora transformer model is a separate thing, it's a text2video model they finetuned alongside Tora, it is not required to use it. You instead use this to load only the trajectory control part:

![image](https://github.com/user-attachments/assets/4a3de3fe-f49f-4461-a260-b3a6d776ea17)

**Comment by jav12z** [comment]
Oh... Many thanks!
