### ISSUE TITLE
Install-Issues under Ubuntu 22.04

### ISSUE THREAD

**Issue by botnang** [kijai/ComfyUI-CogVideoXWrapper#2]
Traceback (most recent call last):
  File "/home/user/AI/comfy-2.0-beta/nodes.py", line 1941, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/user/AI/comfy-2.0-beta/custom_nodes/ComfyUI-CogVideoXWrapper/__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/home/user/AI/comfy-2.0-beta/custom_nodes/ComfyUI-CogVideoXWrapper/nodes.py", line 6, in <module>
    from .pipeline_cogvideox import CogVideoXPipeline
  File "/home/user/AI/comfy-2.0-beta/custom_nodes/ComfyUI-CogVideoXWrapper/pipeline_cogvideox.py", line 24, in <module>
    from diffusers.models import AutoencoderKLCogVideoX, CogVideoXTransformer3DModel
ImportError: cannot import name 'AutoencoderKLCogVideoX' from 'diffusers.models' (/home/user/AI/comfy-2.0-beta/venv/lib/python3.10/site-packages/diffusers/models/__init__.py)

Cannot import /home/user/AI/comfy-2.0-beta/custom_nodes/ComfyUI-CogVideoXWrapper module for custom nodes: cannot import name 'AutoencoderKLCogVideoX' from 'diffusers.models' (/home/user/AI/comfy-2.0-beta/venv/lib/python3.10/site-packages/diffusers/models/__init__.py)

Ubuntu 22.04
Python 3.10.12
Lastest ComfyUI

pip show torch
Name: torch
Version: 2.1.2+cu121
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/user/AI/comfy-2.0-beta/venv/lib/python3.10/site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, triton, typing-extensions
Required-by: accelerate, clip-interrogator, facexlib, fairscale, flash-attn, kornia, open_clip_torch, peft, pytorch-lightning, spandrel, stanza, timm, torchaudio, torchdiffeq, torchmetrics, torchsde, torchvision, transparent-background, ultralytics, ultralytics-thop, xformers

pip show diffusers
Name: diffusers
Version: 0.29.2
Summary: State-of-the-art diffusion in PyTorch and JAX.
Home-page: https://github.com/huggingface/diffusers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/diffusers/graphs/contributors)
Author-email: diffusers@huggingface.co
License: Apache 2.0 License
Location: /home/user/AI/comfy-2.0-beta/venv/lib/python3.10/site-packages
Requires: filelock, huggingface-hub, importlib-metadata, numpy, Pillow, regex, requests, safetensors
Required-by: image-reward

**Comment by guahunyo** [comment]
win10  py311  torch2.3+cu121  same error

**Comment by kijai** [comment]
That error is because the specific diffusers version with their PR is not installed, might have to uninstall diffusers first then installing that:

`pip uninstall diffusers`

`pip install git+https://github.com/huggingface/diffusers.git@878f609aa5ce4a78fea0f048726889debde1d7e8#egg=diffusers`

**Comment by botnang** [comment]
> That error is because the specific diffusers version with their PR is not installed, might have to uninstall diffusers first then installing that:
> 
> `pip uninstall diffusers`
> 
> `pip install git+https://github.com/huggingface/diffusers.git@878f609aa5ce4a78fea0f048726889debde1d7e8#egg=diffusers`

problem solved, thank you:)

**Comment by guahunyo** [comment]
> That error is because the specific diffusers version with their PR is not installed, might have to uninstall diffusers first then installing that:该错误是因为未安装带有 PR 的特定扩散器版本，可能必须先卸载扩散器，然后再安装：
> 
> `pip uninstall diffusers`
> 
> `pip install git+https://github.com/huggingface/diffusers.git@878f609aa5ce4a78fea0f048726889debde1d7e8#egg=diffusers`

problem solved too, thank you:)
