### ISSUE TITLE
can CogVideoXFun sampler set the image width and height automatically?

### ISSUE THREAD

**Issue by dummyapps** [kijai/ComfyUI-CogVideoXWrapper#205]
because cogvideox fun model  can work with  any resolution image, so each time when I create video from image, I have to change the image width and height  of  cogvideoxfun sampler  manually if the input image has different resolution. it would be better to fetch the width and height from input image or add two input to the sampler to get width and height from other nodes automatically.

**Comment by kijai** [comment]
You can convert the width and height widgets to inputs, and get the sizes for example from the resize node:

https://github.com/user-attachments/assets/a4a3d60b-f6b1-4da3-a99e-3fcdec86d898

**Comment by dummyapps** [comment]
> You can convert the width and height widgets to inputs, and get the sizes for example from the resize node:
> 
>  chrome_53fBe3libm.mp4

I'm really appreciate  your help, it works!

**Comment by dummyapps** [comment]
Thank you very much, got it.

---- Replied Message ----
| From | Jukka ***@***.***> |
| Date | 11/08/2024 19:08 |
| To | kijai/ComfyUI-CogVideoXWrapper ***@***.***> |
| Cc | dummyapps ***@***.***>,
Author ***@***.***> |
| Subject | Re: [kijai/ComfyUI-CogVideoXWrapper] can CogVideoXFun sampler set the image width and height automatically? (Issue #205) |

You can convert the width and height widgets to inputs, and get the sizes for example from the resize node:

https://github.com/user-attachments/assets/a4a3d60b-f6b1-4da3-a99e-3fcdec86d898
