### ISSUE TITLE
"Prompt outputs failed validation: Value not in list"

### ISSUE THREAD

**Issue by Gyramuur** [kijai/ComfyUI-CogVideoXWrapper#21]
I've updated ComfyUI, and I installed the latest CogVideoXWrapper through ComfyUI manager via this Git's URL. I've loaded the "cogvideox_5b_example_01.json" workflow, and pointed the Load Clip node to my existing model (t5xxl_fp8_e4m3fn.safetensors).

After hitting queue prompt, I get this error:

Prompt outputs failed validation: Value not in list: format: 'video/nvenc_h264-mp4' not in ['image/gif', 'image/webp', 'video/ProRes', 'video/av1-webm', 'video/h264-mp4', 'video/h265-mp4', 'video/webm']
VHS_VideoCombine:
    - Value not in list: format: 'video/nvenc_h264-mp4' not in ['image/gif', 'image/webp', 'video/ProRes', 'video/av1-webm', 'video/h264-mp4', 'video/h265-mp4', 'video/webm']

**Comment by kijai** [comment]
This is because I forgot the nvenc format selected on the video combine node, it's not supported by all platforms. Just change to some other encode format or recreate the video combine node to get past that.

**Comment by Gyramuur** [comment]
That fixed it, thanks. :) Now getting a separate error but I'll open a different issue.
