### ISSUE TITLE
After I updated CogVideoXWrapper, the node all become red suddenly

### ISSUE THREAD

**Issue by huanggou666** [kijai/ComfyUI-CogVideoXWrapper#212]
Anyone know why?
![image](https://github.com/user-attachments/assets/e36dbbb9-dc64-4138-9980-81b844a6bdc2)

**Comment by kijai** [comment]
Probably need to update diffusers.

**Comment by huanggou666** [comment]
> Probably need to update diffusers.

I redownloaded the new ComfyUI from scratch, and now it works.
