### ISSUE TITLE
Kijai/CogVideoX-5b-1.5

### ISSUE THREAD

**Issue by al-swaiti** [kijai/ComfyUI-CogVideoXWrapper#214]
Hi Kijai, how are you? I consider you one of the best in the field of artificial intelligence, and honestly, I think there is a team under this name that I follow regularly. I always see that you are the first in providing the latest AI technologies to Comfy users and others. Today, I downloaded this tool to experiment with the video feature, and I manually downloaded the "Kijai/CogVideoX-5b-1.5" model. I didn’t find it in the list of available models, so I added it to the code  manually . Could you help me adjust the code before I start studying it?
![image](https://github.com/user-attachments/assets/678f7b8d-5f06-4d4a-8909-94979f92ab87)

**Comment by al-swaiti** [comment]
![image](https://github.com/user-attachments/assets/06e66cd1-3bd2-4028-bd23-05b2ed7ae377)

**Comment by kijai** [comment]
It's under development on it's own branch here.

**Comment by kijai** [comment]
> 嗨 Kijai，I think this is a project worth paying attention to. https://github.com/Kmcode1/SG-I2V

That is for StableVideoDiffusion, we already have Tora for CogVideoX that works very similarly.

**Comment by liangzoey** [comment]
> > 嗨 Kijai，I think this is a project worth paying attention to. https://github.com/Kmcode1/SG-I2V
> 
> That is for StableVideoDiffusion, we already have Tora for CogVideoX that works very similarly.

Yes, they are all great, but this one seems to have additional arbitrary camera movement control.

**Comment by al-swaiti** [comment]
I belive that the video models must be  classified as using loras , which is more important than how many barameters trained on , (train the basic model on just basic movements and cover others by loras )

**Comment by DuckersMcQuack** [comment]
Can we use any of the 5b workflows, but increased from 49 frames to say 240? Or what's the changes needed to do a 10 second one?

And is this model more "dynamic" to choose between 1-10 seconds, but needs to be say 24 fps native, or 12 with interpolation to make it even smoother?

Or if workflow needs to be way different, could you share the basic one needed to test the "test version" out?

**Comment by colaz** [comment]
@DuckersMcQuack 
Tell on the prompt to do things "fast" "rapid" and words like that. Then go to something, like I use Topaz, -> slow motion -> interpolation -> grab last frame and repeat. Final result needs to get a nice fix on the fps you want, after the editing is done. That's my way to extend the take, in my desired fps. Also some color correction between the stitches is needed too.

I shoot an old school Enki-Bilal+anime animation  since yesterday, with Fun-5b-I2V, I have the numbers that work on dystopian anime style I  want to approach (he numbers I see here and there being used are wrong), and I use this tecknique and my imagination to reach my goal. Cogvideo depends HEAVILY on prompting. I tell you that for sure. Flowrence-2 can help.
When it is done I ll post my resulted full shot without sound. Then I ll use sound as well to participate in some online festival or something just for my pleasure. My nickname is @zazoum1 just in case you wanna see it and the "how-to-do-it-process" when it will be posted, BUT I WARN you I do there A LOT of NSFW stuff, so if you are a minor or not into these things don't search for me.
I don't make any money with internet, so this basically this is not an advertisement.

**Comment by al-swaiti** [comment]
https://github.com/user-attachments/assets/97095301-fe60-46c1-b004-01e12c894587
 my first success using Kijai/CogVideoX-5b-1.5

**Comment by kijai** [comment]
> https://github.com/user-attachments/assets/97095301-fe60-46c1-b004-01e12c894587 my first success using Kijai/CogVideoX-5b-1.5

There is still something very wrong with the diffusers implementation when using some resolutions, the old 720x480 included, the results are far better at higher res, for example I2V 1024x608:

https://github.com/user-attachments/assets/461957f1-c9b6-4865-8689-98ca18192696

T2V 768x768:

https://github.com/user-attachments/assets/5d7a8fdf-2a55-4d58-aa04-c49c6d754bb5

Also the beginning being corrupt on T2V is a continuing issue.

**Comment by gitanon112** [comment]
Can you please post workflows? i have no clue how you're getting such good results w/1.5, mine are horrible

**Comment by kijai** [comment]
> Can you please post workflows? i have no clue how you're getting such good results w/1.5, mine are horrible

Workflows are the same, the supported resolutions are different and we don't really know what works best yet, besides the default 1360x768 what has worked for me is 768x768 and 936x640. Generally anything larger than 640 can work, the old default resolution does not work.

**Comment by jpgallegoar** [comment]
@kijai Is it correct that Diffusers is almost completed? [](https://github.com/huggingface/diffusers/pull/9877) Does this mean final merge is coming and we're getting diffusers 1.5?

**Comment by kijai** [comment]
> @kijai Is it correct that Diffusers is almost completed? Does this mean final merge is coming and we're getting diffusers 1.5?

Since the last update it's been working well.

**Comment by jpgallegoar** [comment]
> > @kijai Is it correct that Diffusers is almost completed? Does this mean final merge is coming and we're getting diffusers 1.5?
> 
> Since the last update it's been working well.

I forgot to link this https://github.com/huggingface/diffusers/pull/9877, it's what I was referring to. Are we going to get a different diffusers model or is it the same one you have uploaded?

**Comment by kijai** [comment]
> > > @kijai Is it correct that Diffusers is almost completed? Does this mean final merge is coming and we're getting diffusers 1.5?
> > 
> > 
> > Since the last update it's been working well.
> 
> I forgot to link this [huggingface/diffusers#9877](https://github.com/huggingface/diffusers/pull/9877), it's what I was referring to. Are we going to get a different diffusers model or is it the same one you have uploaded?

It's converted with their script so should be same, it works very nicely currently in the nodes.

**Comment by jpgallegoar** [comment]
> > > > @kijai Is it correct that Diffusers is almost completed? Does this mean final merge is coming and we're getting diffusers 1.5?
> > > 
> > > 
> > > Since the last update it's been working well.
> > 
> > 
> > I forgot to link this [huggingface/diffusers#9877](https://github.com/huggingface/diffusers/pull/9877), it's what I was referring to. Are we going to get a different diffusers model or is it the same one you have uploaded?
> 
> It's converted with their script so should be same, it works very nicely currently in the nodes.

Awesome! I will test it this afternoon, thanks for your awesome work as always!

**Comment by codexq123** [comment]
> > > > > @kijai Is it correct that Diffusers is almost completed? Does this mean final merge is coming and we're getting diffusers 1.5?
> > > > 
> > > > 
> > > > Since the last update it's been working well.
> > > 
> > > 
> > > I forgot to link this [huggingface/diffusers#9877](https://github.com/huggingface/diffusers/pull/9877), it's what I was referring to. Are we going to get a different diffusers model or is it the same one you have uploaded?
> > 
> > 
> > It's converted with their script so should be same, it works very nicely currently in the nodes.
> 
> Awesome! I will test it this afternoon, thanks for your awesome work as always!

How is the video generated by cogvideox 1.5 i2v?  Is it much better than 1.0

**Comment by codexq123** [comment]
> > > > > > > @kijai Is it correct that Diffusers is almost completed? Does this mean final merge is coming and we're getting diffusers 1.5?
> > > > > > 
> > > > > > 
> > > > > > Since the last update it's been working well.
> > > > > 
> > > > > 
> > > > > I forgot to link this [huggingface/diffusers#9877](https://github.com/huggingface/diffusers/pull/9877), it's what I was referring to. Are we going to get a different diffusers model or is it the same one you have uploaded?
> > > > 
> > > > 
> > > > It's converted with their script so should be same, it works very nicely currently in the nodes.
> > > 
> > > 
> > > Awesome! I will test it this afternoon, thanks for your awesome work as always!
> > 
> > 
> > How is the video generated by cogvideox 1.5 i2v? Is it much better than 1.0
> 
> I've been mostly playing with the DimensionX LoRAs with it, the quality is much higher:
> 
>  cogvideo_orbits_00002.mp4 
>  dimensionxoldman_00005.mp4

Thanks for your awesome work. I work for any resolution now. But I will run for a bit long time(8min for bf16 1360*768 49 frames for 3090ti). Great work! Thanks you KJ.

**Comment by horenbergerb** [comment]
> > > > > > > > @kijai Is it correct that Diffusers is almost completed? Does this mean final merge is coming and we're getting diffusers 1.5?
> > > > > > > 
> > > > > > > 
> > > > > > > Since the last update it's been working well.
> > > > > > 
> > > > > > 
> > > > > > I forgot to link this [huggingface/diffusers#9877](https://github.com/huggingface/diffusers/pull/9877), it's what I was referring to. Are we going to get a different diffusers model or is it the same one you have uploaded?
> > > > > 
> > > > > 
> > > > > It's converted with their script so should be same, it works very nicely currently in the nodes.
> > > > 
> > > > 
> > > > Awesome! I will test it this afternoon, thanks for your awesome work as always!
> > > 
> > > 
> > > How is the video generated by cogvideox 1.5 i2v? Is it much better than 1.0
> > 
> > 
> > I've been mostly playing with the DimensionX LoRAs with it, the quality is much higher:
> > cogvideo_orbits_00002.mp4
> > dimensionxoldman_00005.mp4
> 
> Thanks for your awesome work. It work for any resolution now. But it will run for a bit long time(8min for bf16 1360*768 49 frames for 3090ti). Great work! Thank you KJ.

Could you elaborate on your setup? I am using a slightly-modified version of the cogvideox_I2V_example_01.json workflow. On my machine (also a 3090), 512x512 i2v generations work with the 1.5 model, but larger sizes like 768x768 run out of VRAM. The VRAM is relatively low at just under 10GB until the CogVideo Decode node, where it spikes up to like 18-20GB.

My only guess is that maybe it's my CLIP model? I'm using t5xxl_fp8_e4m3fn.safetensors. I am able to increase the number of frames up to the recommended value of 81 without issue though.

**Comment by kijai** [comment]
> > > > > > > > > @kijai Is it correct that Diffusers is almost completed? Does this mean final merge is coming and we're getting diffusers 1.5?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Since the last update it's been working well.
> > > > > > > 
> > > > > > > 
> > > > > > > I forgot to link this [huggingface/diffusers#9877](https://github.com/huggingface/diffusers/pull/9877), it's what I was referring to. Are we going to get a different diffusers model or is it the same one you have uploaded?
> > > > > > 
> > > > > > 
> > > > > > It's converted with their script so should be same, it works very nicely currently in the nodes.
> > > > > 
> > > > > 
> > > > > Awesome! I will test it this afternoon, thanks for your awesome work as always!
> > > > 
> > > > 
> > > > How is the video generated by cogvideox 1.5 i2v? Is it much better than 1.0
> > > 
> > > 
> > > I've been mostly playing with the DimensionX LoRAs with it, the quality is much higher:
> > > cogvideo_orbits_00002.mp4
> > > dimensionxoldman_00005.mp4
> > 
> > Thanks for your awesome work. It work for any resolution now. But it will run for a bit long time(8min for bf16 1360*768 49 frames for 3090ti). Great work! Thank you KJ.
> 
> Could you elaborate on your setup? I am using a slightly-modified version of the cogvideox_I2V_example_01.json workflow. On my machine (also a 3090), 512x512 i2v generations work with the 1.5 model, but larger sizes like 768x768 run out of VRAM. The VRAM is relatively low at just under 10GB until the CogVideo Decode node, where it spikes up to like 18-20GB.
> 
> My only guess is that maybe it's my CLIP model? I'm using t5xxl_fp8_e4m3fn.safetensors. I am able to increase the number of frames up to the recommended value of 81 without issue though.

If you run out of memory on the decode, you need to enable the tiling option in the node.

**Comment by horenbergerb** [comment]
> > > > > > > > > > @kijai Is it correct that Diffusers is almost completed? Does this mean final merge is coming and we're getting diffusers 1.5?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Since the last update it's been working well.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > I forgot to link this [huggingface/diffusers#9877](https://github.com/huggingface/diffusers/pull/9877), it's what I was referring to. Are we going to get a different diffusers model or is it the same one you have uploaded?
> > > > > > > 
> > > > > > > 
> > > > > > > It's converted with their script so should be same, it works very nicely currently in the nodes.
> > > > > > 
> > > > > > 
> > > > > > Awesome! I will test it this afternoon, thanks for your awesome work as always!
> > > > > 
> > > > > 
> > > > > How is the video generated by cogvideox 1.5 i2v? Is it much better than 1.0
> > > > 
> > > > 
> > > > I've been mostly playing with the DimensionX LoRAs with it, the quality is much higher:
> > > > cogvideo_orbits_00002.mp4
> > > > dimensionxoldman_00005.mp4
> > > 
> > > 
> > > Thanks for your awesome work. It work for any resolution now. But it will run for a bit long time(8min for bf16 1360*768 49 frames for 3090ti). Great work! Thank you KJ.
> > 
> > 
> > Could you elaborate on your setup? I am using a slightly-modified version of the cogvideox_I2V_example_01.json workflow. On my machine (also a 3090), 512x512 i2v generations work with the 1.5 model, but larger sizes like 768x768 run out of VRAM. The VRAM is relatively low at just under 10GB until the CogVideo Decode node, where it spikes up to like 18-20GB.
> > My only guess is that maybe it's my CLIP model? I'm using t5xxl_fp8_e4m3fn.safetensors. I am able to increase the number of frames up to the recommended value of 81 without issue though.
> 
> If you run out of memory on the decode, you need to enable the tiling option in the node.

Thanks, that fixed it. Do you have any recommendations for the tile width and height? I am setting them equal to the image/video width/height since that seems to be what the example did.

**Comment by kijai** [comment]
> > > > > > > > > > > @kijai Is it correct that Diffusers is almost completed? Does this mean final merge is coming and we're getting diffusers 1.5?
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > Since the last update it's been working well.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > I forgot to link this [huggingface/diffusers#9877](https://github.com/huggingface/diffusers/pull/9877), it's what I was referring to. Are we going to get a different diffusers model or is it the same one you have uploaded?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > It's converted with their script so should be same, it works very nicely currently in the nodes.
> > > > > > > 
> > > > > > > 
> > > > > > > Awesome! I will test it this afternoon, thanks for your awesome work as always!
> > > > > > 
> > > > > > 
> > > > > > How is the video generated by cogvideox 1.5 i2v? Is it much better than 1.0
> > > > > 
> > > > > 
> > > > > I've been mostly playing with the DimensionX LoRAs with it, the quality is much higher:
> > > > > cogvideo_orbits_00002.mp4
> > > > > dimensionxoldman_00005.mp4
> > > > 
> > > > 
> > > > Thanks for your awesome work. It work for any resolution now. But it will run for a bit long time(8min for bf16 1360*768 49 frames for 3090ti). Great work! Thank you KJ.
> > > 
> > > 
> > > Could you elaborate on your setup? I am using a slightly-modified version of the cogvideox_I2V_example_01.json workflow. On my machine (also a 3090), 512x512 i2v generations work with the 1.5 model, but larger sizes like 768x768 run out of VRAM. The VRAM is relatively low at just under 10GB until the CogVideo Decode node, where it spikes up to like 18-20GB.
> > > My only guess is that maybe it's my CLIP model? I'm using t5xxl_fp8_e4m3fn.safetensors. I am able to increase the number of frames up to the recommended value of 81 without issue though.
> > 
> > If you run out of memory on the decode, you need to enable the tiling option in the node.
> 
> Thanks, that fixed it. Do you have any recommendations for the tile width and height? I am setting them equal to the image/video width/height since that seems to be what the example did.

It has the auto_tile_size option that should be on by default, with that you don't need to worry about the tile sizes. If it would still run out of memory or if you see the tile seams, then you can disable the auto option and manually try different sizes/overlap.

**Comment by mikeyimer** [comment]
> > > > > > > > > > > > @kijai Is it correct that Diffusers is almost completed? Does this mean final merge is coming and we're getting diffusers 1.5?
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > Since the last update it's been working well.
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > I forgot to link this [huggingface/diffusers#9877](https://github.com/huggingface/diffusers/pull/9877), it's what I was referring to. Are we going to get a different diffusers model or is it the same one you have uploaded?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > It's converted with their script so should be same, it works very nicely currently in the nodes.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Awesome! I will test it this afternoon, thanks for your awesome work as always!
> > > > > > > 
> > > > > > > 
> > > > > > > How is the video generated by cogvideox 1.5 i2v? Is it much better than 1.0
> > > > > > 
> > > > > > 
> > > > > > I've been mostly playing with the DimensionX LoRAs with it, the quality is much higher:
> > > > > > cogvideo_orbits_00002.mp4
> > > > > > dimensionxoldman_00005.mp4
> > > > > 
> > > > > 
> > > > > Thanks for your awesome work. It work for any resolution now. But it will run for a bit long time(8min for bf16 1360*768 49 frames for 3090ti). Great work! Thank you KJ.
> > > > 
> > > > 
> > > > Could you elaborate on your setup? I am using a slightly-modified version of the cogvideox_I2V_example_01.json workflow. On my machine (also a 3090), 512x512 i2v generations work with the 1.5 model, but larger sizes like 768x768 run out of VRAM. The VRAM is relatively low at just under 10GB until the CogVideo Decode node, where it spikes up to like 18-20GB.
> > > > My only guess is that maybe it's my CLIP model? I'm using t5xxl_fp8_e4m3fn.safetensors. I am able to increase the number of frames up to the recommended value of 81 without issue though.
> > > 
> > > 
> > > If you run out of memory on the decode, you need to enable the tiling option in the node.
> > 
> > 
> > Thanks, that fixed it. Do you have any recommendations for the tile width and height? I am setting them equal to the image/video width/height since that seems to be what the example did.
> 
> It has the auto_tile_size option that should be on by default, with that you don't need to worry about the tile sizes. If it would still run out of memory or if you see the tile seams, then you can disable the auto option and manually try different sizes/overlap.

A question,if fp8_transformer is set to enable, will the final sampling use fp8 even if I select fp16 in precision?

**Comment by kijai** [comment]
> A question,if fp8_transformer is set to enable, will the final sampling use fp8 even if I select fp16 in precision?

Enabling fp8_transformer will cast most of the weights of the model to fp8, reducing the amount of memory it reserves. Many of the actual operations within the model can't or shouldn't be done in fp8, such as attention, those are run with the selected precision, as well as the VAE.

**Comment by codexq123** [comment]
> > > > > > > > > @kijai Is it correct that Diffusers is almost completed? Does this mean final merge is coming and we're getting diffusers 1.5?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Since the last update it's been working well.
> > > > > > > 
> > > > > > > 
> > > > > > > I forgot to link this [huggingface/diffusers#9877](https://github.com/huggingface/diffusers/pull/9877), it's what I was referring to. Are we going to get a different diffusers model or is it the same one you have uploaded?
> > > > > > 
> > > > > > 
> > > > > > It's converted with their script so should be same, it works very nicely currently in the nodes.
> > > > > 
> > > > > 
> > > > > Awesome! I will test it this afternoon, thanks for your awesome work as always!
> > > > 
> > > > 
> > > > How is the video generated by cogvideox 1.5 i2v? Is it much better than 1.0
> > > 
> > > 
> > > I've been mostly playing with the DimensionX LoRAs with it, the quality is much higher:
> > > cogvideo_orbits_00002.mp4
> > > dimensionxoldman_00005.mp4
> > 
> > 
> > Thanks for your awesome work. It work for any resolution now. But it will run for a bit long time(8min for bf16 1360*768 49 frames for 3090ti). Great work! Thank you KJ.
> 
> Could you elaborate on your setup? I am using a slightly-modified version of the cogvideox_I2V_example_01.json workflow. On my machine (also a 3090), 512x512 i2v generations work with the 1.5 model, but larger sizes like 768x768 run out of VRAM. The VRAM is relatively low at just under 10GB until the CogVideo Decode node, where it spikes up to like 18-20GB.
> 
> My only guess is that maybe it's my CLIP model? I'm using t5xxl_fp8_e4m3fn.safetensors. I am able to increase the number of frames up to the recommended value of 81 without issue though.

enable vae tiling would help this

**Comment by zazoum-art** [comment]
@horenbergerb
`My only guess is that maybe it's my CLIP model? I'm using t5xxl_fp8_e4m3fn.safetensors. I am able to increase the number of frames up to the recommended value of 81 without issue though.`

I manage to do 125 frames with 4090, while doing a big DimensionX LoRA rotation. My goal is a full 360 rotation.
[i2v4.json](https://github.com/user-attachments/files/17794770/i2v4.json)

**Comment by kijai** [comment]
Merged along with a big refactor, please read the readme. Closing this one.
