### ISSUE TITLE
after 11.12 upgrade CogvideoFunX sample errer

### ISSUE THREAD

**Issue by littleyeson** [kijai/ComfyUI-CogVideoXWrapper#224]
![01](https://github.com/user-attachments/assets/489e2bd4-9b43-4cad-b7d3-678c85e40818)
![02](https://github.com/user-attachments/assets/980e1561-e4f8-45fc-babd-09b890350088)
![03](https://github.com/user-attachments/assets/3372123e-c9fc-4680-8ddd-8b7c70505100)

**Comment by kijai** [comment]
Width 856 doesn't work with DPM++ apparently, I've changed nothing about this so probably always has been so, works with DDIM. 

Fun sampler did get changed and you do need to remake it, it's possible this changed the default sampler too for you.
