### ISSUE TITLE
mat1 and mat2 shapes cannot be multiplied

### ISSUE THREAD

**Issue by TRONBFFL** [kijai/ComfyUI-CogVideoXWrapper#236]
Getting this error running in my linux hosted comfyui but not on my windows machine. Any thoughts?

<img width="846" alt="image" src="https://github.com/user-attachments/assets/0a8d26c5-ad36-46e0-b6f8-5f48de5b0110">

**Comment by zazoum-art** [comment]
I was getting that in python 3-11 without deepspeed installed when running Fun model. Do you run the Fun model?

**Comment by TRONBFFL** [comment]
I am running 3-11 and I am using the Fun model. I notice Deepseed was not installed - will give it a shot. Thanks!

**Comment by TRONBFFL** [comment]
verified Deepspeed installed now - still no love, same error. 
<img width="799" alt="image" src="https://github.com/user-attachments/assets/bf901970-1683-4525-ac39-60021fb2c155">

**Comment by kijai** [comment]
Almost looks like wrong text encoder?

**Comment by zazoum-art** [comment]
Check the Fun folders tree structure as well:

📦 models/
├── 📂 Diffusion_Transformer/
│   ├── 📂 CogVideoX-Fun-V1.1-2b-InP/
│   └── 📂 CogVideoX-Fun-V1.1-5b-InP/
├── 📂 Personalized_Model/
│   └── your trained trainformer model / your trained lora model (for UI load)

**Comment by TRONBFFL** [comment]
I'm using the gguf. And it is auto downloading to app/ComfyUI/models/CogVideo/GGUF/CogVideoX_5b_fun_1_1_GGUF_Q4_0.safetensors
<img width="734" alt="image" src="https://github.com/user-attachments/assets/c08a0ce8-79fd-4e86-9f3a-b1d06c2b95f6">

**Comment by kijai** [comment]
> I'm using the gguf. And it is auto downloading to app/ComfyUI/models/CogVideo/GGUF/CogVideoX_5b_fun_1_1_GGUF_Q4_0.safetensors <img alt="image" width="734" src="https://private-user-images.githubusercontent.com/144924710/386718678-c08a0ce8-79fd-4e86-9f3a-b1d06c2b95f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2OTYxMjUsIm5iZiI6MTczMTY5NTgyNSwicGF0aCI6Ii8xNDQ5MjQ3MTAvMzg2NzE4Njc4LWMwOGEwY2U4LTc5ZmQtNGU4Ni05ZjNhLWIxZDA2YzJiOTVmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQxODM3MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODU4MjhjYzM5NWRjOWU1ZDllZjQ0ZTJiZjQ5MTVkNzhkN2ZjNWI5ZDU4ZjMyNDZkN2E4ZmRkY2NlNjcwNTg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6IRTjcq7PiVp63lWYbdarlD_rno5GWBgp4H9pMCUx9E">

Nothing to do with the CogVideoX model then if it errors on the text encoder already, I don't know why it would, besides maybe ComfyUI itself being very out of date.

**Comment by TRONBFFL** [comment]
I checked the git version of Comfyui and it says _latest_. hmm.

**Comment by zazoum-art** [comment]
are you using this specific gguf workflow both in linux AND win and it works only on win?

**Comment by TRONBFFL** [comment]
yes same workflow on both, it works in windows. I'm exploring the versioning info of comfyui as on the linux side I am using this canned comfy docker install on an inference host. I thought I read it was the latest comfy, but now I'm doubting it. And also, as a test, I made my own virutal linux box on my machine and it worked there too. So there has to be something wrong with this canned install.

**Comment by TRONBFFL** [comment]
yeah once I built it from scratch it worked my comfyui was old.
