### ISSUE TITLE
Spline editor not working

### ISSUE THREAD

**Issue by Ka1-Fun** [kijai/ComfyUI-CogVideoXWrapper#238]
I'm trying to use spline editor for CogvideoX tora workflow. It's not working at all and node doesn't seem to have same settings/parameters as material found on tutorials. 

Here's how it looks, if I press new spline, nothing happens.
![image](https://github.com/user-attachments/assets/25391982-a73e-4069-9820-87813f7ea8c3)

If I press the icon on top right this window opens
![image](https://github.com/user-attachments/assets/ef496fa0-7b85-4e60-aee9-11aff32d0a8a)

Anyone run onto same issue perhaps or might know how to get this working?

**Comment by kijai** [comment]
It looks like really old version of the node, are you sure KJNodes is up to date? And if it is, try removing that node and readding it.

**Comment by Ka1-Fun** [comment]
Yeah it's been updated and I've also tried removing and readding it.  I reinstalled it and now it looks like this..
![image](https://github.com/user-attachments/assets/d0329ae1-65b3-4be3-a69e-48a06ff8f886)

**Comment by kijai** [comment]
> Yeah it's been updated and I've also tried removing and readding it.  I reinstalled it and now it looks like this..
> ![image](https://github.com/user-attachments/assets/d0329ae1-65b3-4be3-a69e-48a06ff8f886)
> 

Oh I know what's going on, you have KJNodes installed twice, it's pulling this from another folder which you have at some point manually installed, I can see from the "-main" in the name above the node. Delete that folder from your custom nodes.

**Comment by Ka1-Fun** [comment]
That's it! Nyt toimii, kiitos! :)
