### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooSmall

### ISSUE THREAD

**Issue by TRONBFFL** [kijai/ComfyUI-CogVideoXWrapper#239]
OK - got a new error - thoughts? thanks as always

I'm running
transformers==4.46.2
safetensors==0.4.5

 <img width="692" alt="image" src="https://github.com/user-attachments/assets/7e3b0b32-e7f0-48ab-a629-c0e77e98db70">

**Comment by kijai** [comment]
Corrupt/incomplete model file.

**Comment by TRONBFFL** [comment]
hmm ok, which model file?

**Comment by kijai** [comment]
Can't see full error, but text encoder by the looks of it.

**Comment by TRONBFFL** [comment]
Not entirely sure what I did to get it to work. But it is working now. Thank you for the help!
