### ISSUE TITLE
download cogVideoX-5b-12v always error

### ISSUE THREAD

**Issue by GodLyons** [kijai/ComfyUI-CogVideoXWrapper#241]
![image](https://github.com/user-attachments/assets/c30fef36-5060-4b65-b25b-01152a034e5f)
when i download ComfyUI-CogVideoXWrapper and run his example,it will download this model auto,but i always get error when i download 12v,can you privide another way to download it?by the way,i just know python a little.thank you!

**Comment by zazoum-art** [comment]
Had the same problem with kijai 5b-1.5. Practically thinking, I immediately deleted the whole models 5b-1.5 folders, went to huggingface, downloaded all files one by one, 17 of them, in the models 5b-1.5 folder in the hugginghace correct subfolders, instantly worked. I don't know what was wrong, I don't know why it worked, I don't care, I can make guesses, it was an instant decision and a 15 minutes download burden.
The result is that it is working now.

**Comment by GodLyons** [comment]
> Had the same problem with kijai 5b-1.5 (config.json missing). Practically thinking, I immediately deleted the whole models 5b-1.5 folders, went to huggingface, downloaded all files one by one, 17 of them, in the models 5b-1.5 folder in the hugginghace correct subfolders, instantly worked. I don't know what was wrong, I don't know why it worked, I don't care, I can make guesses, it was an instant decision and a 15 minutes download burden. The result is that it is working now.

thanks， i download it from huggingface
