### ISSUE TITLE
🔥🔥 News: 2024/11/15: THUDM released the CogVideoX1.5 model in the diffusers version. 

### ISSUE THREAD

**Issue by ptits** [kijai/ComfyUI-CogVideoXWrapper#243]

**Comment by kijai** [comment]
It's been working in the test branch for a week already, properly for couple of days. I'm taking the opportunity to work on bigger overall update to the nodes to better align it to ComfyUI standards.

**Comment by zazoum-art** [comment]
Now that you mention a nodes update. Is it possible to add a first/last frame functionality to Cogvideo Sampler, just as the Fun Sampler has?

**Comment by kijai** [comment]
> Now that you mention a nodes update. Is it possible to add a first/last frame functionality to Cogvideo Sampler, just as the Fun Sampler has?

It is already possible with this nodes:

![image](https://github.com/user-attachments/assets/19b2f22d-04ba-455b-85a1-7999bc067d2f)

Note that while this seems to work with all the I2V models, only one model is trained for interpolation, so results will vary. Works surprisingly good with 1.5 though.
