### ISSUE TITLE
lower 1/6th showing distortion

### ISSUE THREAD

**Issue by unclemusclez** [kijai/ComfyUI-CogVideoXWrapper#248]
https://github.com/user-attachments/assets/06524279-307d-46d9-96e5-fc82309926ba

thanks for any help. this seems to be consistent

**Comment by kijai** [comment]
This is generated at 720x480? Never seen that happen before and unable to replicate if so...

**Comment by unclemusclez** [comment]
I think this may be an issue with VAE tiling and the fact I am using AMD Navi 31.

If I disable tiling, it works. I have 20GB to work with, but with previous workflows I would run out of VRAM. The recent updates to pytorch may have also helped. 

All of my issues will pertain to AMD, so if you ignore me I will not be offended. 😅

**Comment by kijai** [comment]
I didn't even know this works on AMD, but yeah.. not much I can do about that I'm afraid.

**Comment by unclemusclez** [comment]
i like to document the issues i have at least for other people's reference. AMD developers also are actively enhancing compatibility daily. 

This node rocks thanks for the help. i'm going to leave this open in case I figure out more information, I'm working with CogX a lot currently.

**Comment by kijai** [comment]
> i like to document the issues i have at least for other people's reference. AMD developers also are actively enhancing compatibility daily.
> 
> This node rocks thanks for the help. i'm going to leave this open in case I figure out more information, I'm working with CogX a lot currently.

You could try with the latest update (it's a big one and does require fixing old workflows), as it allows running the VAE with fp32, which may work better. The fp32 VAE is available here: 

https://huggingface.co/Kijai/CogVideoX-comfy/blob/main/cogvideox_vae_fp32.safetensors

**Comment by unclemusclez** [comment]
closing this under "AMD Problems"
