### ISSUE TITLE
add VEnhancer please

### ISSUE THREAD

**Issue by al3dv2** [kijai/ComfyUI-CogVideoXWrapper#25]
VEnhancer improve the quality of CogvideoX video https://github.com/Vchitect/VEnhancer
Is it possible to add it to the Comfyui workflow ? thanks

**Comment by kijai** [comment]
I did make nodes for it before, haven't had time to properly test it, it works but is pretty hard to choose correct settings: https://github.com/kijai/ComfyUI-VEnhancer

**Comment by al3dv2** [comment]
Ok thanks !
