### ISSUE TITLE
Error no file named diffusion_pytorch_model.bin ...

### ISSUE THREAD

**Issue by GeffersAtWork** [kijai/ComfyUI-CogVideoXWrapper#269]
Using the example workflow for 1.5 I2V from github.

Manually downloaded all the files I could find on hugging face, all boxes are good, but that message pops up before anything happens.

"Error no file named diffusion_pytorch_model.bin found in directory C:\ComfyUI_windows_portable\ComfyUI\models\CogVideo\CogVideoX-5b-1.5."

**Comment by KrakeyMTL** [comment]
It didn't fully download all the files. I get this sometimes when I manually put them in - comfyui likes to..do things by itself. annoying.

I got around this by using the built in node downloader that Kijai set into the wrapper.

When comfyui "fetches" itself it works. odd I know but I get it randomly as well. I think this is more a comfy thing

**Comment by kijai** [comment]
Huggingface downloader occasionally has these issues especially with large files, I've started to setup alternative cleaner way of getting the models which can be loaded with these new nodes:

![image](https://github.com/user-attachments/assets/b4b7f8e2-9920-4526-bb52-de7f49391b84)

![image](https://github.com/user-attachments/assets/b21fab97-ea0e-4557-9709-7ffae6abce6a)

Not all models are converted yet, but I have the 1.5 available here:

https://huggingface.co/Kijai/CogVideoX-comfy/tree/main

The models go to the normal `ComfyUI/models/diffusion_models` folder and VAE to `ComfyUI/models/vae`

**Comment by GeffersAtWork** [comment]
Thanks, much appreciated, downloading now.

**Comment by kijai** [comment]
> Well, downloaded those files, but it doesn't help. Still getting that specific file missing, and it's true, it doesn't exist. "diffusion_pytorch_model.bin" - where is it? There is a version of it in the previous version folder. CogvideoXWrapper is highlighted, suggesting it's a file missing related to the CogVideo Downloader. ![Diffusion](https://private-user-images.githubusercontent.com/141028886/388452619-6497b2ff-8072-41e5-b1c4-81386506acc4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxOTE1NDUsIm5iZiI6MTczMjE5MTI0NSwicGF0aCI6Ii8xNDEwMjg4ODYvMzg4NDUyNjE5LTY0OTdiMmZmLTgwNzItNDFlNS1iMWM0LTgxMzg2NTA2YWNjNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQxMjE0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDE5ZGVhYTc0OTgwZmE1NTJmYTdjZTk4NTQ1MmU2ZThjMDYzNTZjNGI0MTdhNjJiZDkyODhkNjA1YmVhNjI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.rdNH35LiOOBRKwasoOOAX97XMJlwNc6t1i3r-Isbc1g)

Use the another node I showed above, not the download node.

**Comment by GeffersAtWork** [comment]
Yes, I had put them there too... Thanks okay  looks better now - I was using the example workflow from github in the examples folder, but it evidently isn't updated so was using the old nodes. cheers :-)

**Comment by GeffersAtWork** [comment]
Thanks all. Example workflow needed the nodes changing to the new ones.
