### ISSUE TITLE
Unable to load weights from checkpoint file

### ISSUE THREAD

**Issue by tetsuoo-online** [kijai/ComfyUI-CogVideoXWrapper#27]
CogVideoX-5b doesn't work, it seem to be a file issue :
![{6AE040EB-C737-4873-B540-410659DA5CF9}](https://github.com/user-attachments/assets/c748f840-9fe6-41cc-a090-58f4067f3940)
There are actually 2 files on HuggingFace not 1 :
![image](https://github.com/user-attachments/assets/1ceec62a-591c-4277-8f9c-1beaedcde207)

Here's my attempt to rename the files using a hardlink but no luck. The smaller file (02 of 02) was already downloaded automatically so I tried that too. Am I supposed to combine them in some way maybe ?
![image](https://github.com/user-attachments/assets/f971765b-a3e6-4174-9430-25932473ef65)

Note, I have 3090/24GB and the requirements are successfully installed :
![image](https://github.com/user-attachments/assets/b0709c6e-ba2e-436a-bd0a-2036e7aaaa63)
![image](https://github.com/user-attachments/assets/7764d404-341c-4fa7-b718-0ff8eb37018a)

**Comment by kijai** [comment]
It's diffusers format so the model is the folder itself, not any of the files. There shouldn't be a .bin file at all, just what you see in the online folder.

**Comment by tetsuoo-online** [comment]
> It's diffusers format so the model is the folder itself, not any of the files. There shouldn't be a .bin file at all, just what you see in the online folder.

I understand but then why is it asking for a .bin file ? At first there was only 'diffusion_pytorch_model-00002-of-00002.safetensors' file with config.json, downloaded automatically. I added manually the other json and the first part 'diffusion_pytorch_model-00001-of-00002', hoping that it would help but it didn't.

![image](https://github.com/user-attachments/assets/53505da5-fa81-41b0-844a-c90d01bcf9af)

**Comment by tetsuoo-online** [comment]
I removed the folder so that it can be downloaded again. Let's see what happens
![image](https://github.com/user-attachments/assets/b5585ba1-d51b-4c8a-abec-41597c8b461c)
