### ISSUE TITLE
Prompt outputs failed validation CogVideoDecode: - Exception when validating inner node: tuple index out of range

### ISSUE THREAD

**Issue by andrewssdd** [kijai/ComfyUI-CogVideoXWrapper#272]
Text-to-video workflow failing at cogvideo decode node after update.

[cogvideo-5b-v2.json](https://github.com/user-attachments/files/17839168/cogvideo-5b-v2.json)

**Comment by kijai** [comment]
Please read  the readme that I updated with this big update, old workflows do not work as they are, you would either have to refresh (right click and fix node, or re-create the offending node) or use one of the new example workflows after updating.

**Comment by andrewssdd** [comment]
The new text to video json in the examples folder works. Thank you!
