### ISSUE TITLE
More Tokens - I found a solution? or is it a delusional practice? Kijai 1.5 model tested only.

### ISSUE THREAD

**Issue by zazoum-art** [kijai/ComfyUI-CogVideoXWrapper#289]
Ok, as I had enough with atrocious tennis sports footage cause of the racket and racket net constantly getting deformed, I thought I should train a lora, but then again I found that too tiresome.
So, I did the following:

(1) Changed this line:
**_"max_text_seq_length": 452,_**   from 226 to int 452, the \models\CogVideo\CogVideoX-5b-1.5\transformer_I2V\config.json

and

(2) this  line in nodes.py (previous test branch):
**_max_tokens = 452_**
        load_device = mm.text_encoder_device()
        offload_device = mm.text_encoder_offload_device()
        clip.tokenizer.t5xxl.pad_to_max_length = True
        clip.tokenizer.t5xxl.max_length = max_tokens
        clip.cond_stage_model.to(load_device)
        tokens = clip.tokenize(prompt, return_word_ids=True)
        embeds = clip.encode_from_tokens(tokens, return_pooled=False, return_dict=False)
        if embeds.shape[1] > max_tokens:
            raise ValueError(f"Prompt is too long, max tokens supported is {max_tokens} or less, got {embeds.shape[1]}")

(3) Restarted comfyUI, spammed the already tokens limit reached negative prompt with tennis racket corrections
(4) Run the workflow and it run normally

and I get some better(not perfect yet) results like this better 360 racket rotation:

https://github.com/user-attachments/assets/70aeed7e-c2d6-438d-abda-104bd9133d43

compared to some previous tests like this atrocity:

https://github.com/user-attachments/assets/19b1a6c1-b97f-47c6-8e87-d13d2a6aa1b1

Is this a delusion, that it is getting fixed? Do the changes in the code have any logical base programmatically? I know nothing on coding except some Unity C#. I can't tell. Is ESPECIALLY the kijai 1.5 model bound to 226 or I am doing this the correct way towards a solution?
I ll keep testing.

**Comment by kijai** [comment]
The models are trained with 226, using more will not work as intended, it will change the results of course, but you would need to do a lot of runs to see if it's anything but randomness.

**Comment by zazoum-art** [comment]
Thanks I ll train a lora then.
