### ISSUE TITLE
ValueError: Trying to set a tensor of shape torch.Size([3072, 128]) in "weight" (which has shape torch.Size([3072, 256])), this looks incorrect.

### ISSUE THREAD

**Issue by gladmustang** [kijai/ComfyUI-CogVideoXWrapper#291]
Hi Kijai,
I am trying to use the 1.5 I2V workflow, but get this error, I alreay update the diffuser from the latest src, but it does not work.
Can you advise the possible reason for this, thanks.
My setting as below:
![image](https://github.com/user-attachments/assets/ba206188-176f-442f-ab65-9c0b718220f6)

the rest of setting all the same as example file.

error log below:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\tools\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\tools\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\tools\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\model_loading.py", line 215, in loadmodel
    transformer = CogVideoXTransformer3DModel.from_pretrained(base_path, subfolder=subfolder)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\tools\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "E:\tools\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\modeling_utils.py", line 886, in from_pretrained
    accelerate.load_checkpoint_and_dispatch(
  File "E:\tools\ComfyUI_windows_portable\python_embeded\Lib\site-packages\accelerate\big_modeling.py", line 613, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(
  File "E:\tools\ComfyUI_windows_portable\python_embeded\Lib\site-packages\accelerate\utils\modeling.py", line 1780, in load_checkpoint_in_model
    set_module_tensor_to_device(
  File "E:\tools\ComfyUI_windows_portable\python_embeded\Lib\site-packages\accelerate\utils\modeling.py", line 286, in set_module_tensor_to_device
    raise ValueError(
ValueError: Trying to set a tensor of shape torch.Size([3072, 128]) in "weight" (which has shape torch.Size([3072, 256])), this looks incorrect.

**Comment by kijai** [comment]
I don't know how or why, but it's trying to load image2video model weights into text2video model config, did you use auto download or manually downloaded the files?

**Comment by gladmustang** [comment]
I manually download model files from https://huggingface.co/Kijai/CogVideoX-5b-1.5/tree/main/transformer_I2V, local file like this:
CogVideoX-5b-1.5 folder:
![image](https://github.com/user-attachments/assets/bc7716d3-2a1a-471f-a916-e44fbdbd8b9d)
transformer_I2V foldere:

![image](https://github.com/user-attachments/assets/2f26ca47-e717-48e3-bde2-cd54ae432add)

**Comment by kijai** [comment]
Make sure the config.json is for the right model

**Comment by gladmustang** [comment]
This is the config.json file content, it seems the same as in huggingface.
{
  "_class_name": "CogVideoXTransformer3DModel",
  "_diffusers_version": "0.31.0",
  "activation_fn": "gelu-approximate",
  "attention_bias": true,
  "attention_head_dim": 64,
  "dropout": 0.0,
  "flip_sin_to_cos": true,
  "freq_shift": 0,
  "in_channels": 32,
  "max_text_seq_length": 226,
  "norm_elementwise_affine": true,
  "norm_eps": 1e-05,
  "num_attention_heads": 48,
  "num_layers": 42,
  "ofs_embed_dim": 512,
  "out_channels": 16,
  "patch_bias": false,
  "patch_size": 2,
  "patch_size_t": 2,
  "sample_frames": 81,
  "sample_height": 300,
  "sample_width": 300,
  "spatial_interpolation_scale": 1.875,
  "temporal_compression_ratio": 4,
  "temporal_interpolation_scale": 1.0,
  "text_embed_dim": 4096,
  "time_embed_dim": 512,
  "timestep_activation_fn": "silu",
  "use_learned_positional_embeddings": false,
  "use_rotary_positional_embeddings": true
}

**Comment by gladmustang** [comment]
Thanks a lot, it works now.
