### ISSUE TITLE
KiJai, do you notice LTX Video?

### ISSUE THREAD

**Issue by dummyapps** [kijai/ComfyUI-CogVideoXWrapper#292]
it a 2b video model, I tested it, its i2v is about 10 times faster than cogvideo 5b with faster cache enabled, and the quality is better than cogvideo fun 2b, even better than cogvideo fun 5b.

on my 4060ti 16G, create a 576x1024, 25 frame, 30 steps, the time of whole process  is about 28 seconds, cogvideo 1.5 5b + faster cache needs more than 200 seconds.

**Comment by kijai** [comment]
I'm in the test group yes, it is fast and promising, can't agree with the quality being on par with 5b though, it's fine on some stuff but being smaller model it can't do everything as well (yet). What ultimately matters most is how it will be to further rain, LoRAs and control methods especially as they are the most interesting things we have available for CogVideoX.

**Comment by cheezecrisp** [comment]
Tried it too but found not so good. For i2v it probably produces static videos no matter what the prompt is, I think the cogvideox 2b i2v (not the fun version) dose better in i2v staff.

**Comment by zazoum-art** [comment]
Just tried it. I can't get as much direction as I can with 1.5, but that doesn't mean necessary that the LTX is bad. It is new and it could probably be me not knowing how to prompt it.
What is important for me, (I'm talking about myself specifically and ONLY) is the models to be trained in low res footage, and get good results. I do max 213 frames in one run with a clean 4090 at 624x624, taking 17:50 minutes (no off-load) in 1.5. That's what can fit in a 4090. I up-scale with Topaz to whatever res I want. Below 624px 1.5 it just doesn't work.
Well, LTX beats that by FAR.
So, what remains is the quality, for which, I repeat, LTX is still new.

I'm a fan of whatever can do uncensored content open-source locally. No matter what the well-known companies do, no matter what they achieve, it is useless just by the fact they censor blood and nudity.

**Comment by dummyapps** [comment]
> Tried it too but found not so good. For i2v it probably produces static videos no matter what the prompt is, I think the cogvideox 2b i2v (not the fun version) dose better in i2v task.


It has a relatively good effect on standing postures and sitting postures.

**Comment by dummyapps** [comment]
> Just tried it. I can't get as much direction as I can with 1.5, but that doesn't mean necessary that the LTX is bad. It is new 

CogVideo 1.5 is much better than LTX Video at present. but I feel  LTX is much better than cogvideo 2b fun, it is useful when I try to animate photo just for fun because it is so fast, happy to see that i2v could be so fast,This has made me have great hopes for AI videos.

**Comment by zazoum-art** [comment]
> > Just tried it. I can't get as much direction as I can with 1.5, but that doesn't mean necessary that the LTX is bad. It is new
> 
>This has made me have great hopes for AI videos.

This, TOTALLY this is my feeling as well.
As a Msc. on multimedia holder I have one clean 4090 running cog 1.5 24/7 almost 3 weeks for my true wish for my life (participation on Short Film Festivals), and one clean 4090 for cg boring job (such as porn industry, and marketing companies in a country that has NO single idea on what AI can do -no antagonism) that is funding my wish expenses. Kijai and others I follow (I don't know if I can mention them here) are very important people for me.
And now comes LTX. I hope both uncensored models to be developed even further. And they will. And more new models will come.
