### ISSUE TITLE
abnormal results with fun_1.1_2b

### ISSUE THREAD

**Issue by cheezecrisp** [kijai/ComfyUI-CogVideoXWrapper#295]
https://github.com/user-attachments/assets/84756d7a-479c-4a64-8b9d-6c08eef89981

It's OK with fun_1.1_5b, but abnormal with fun_1.1_2b. Just tried fp16/bf16, various resolution, vae tiling on/off...alwayse like this.

**Comment by kijai** [comment]
Pretty sure 5b just supports more resolutions, noticed it before when trying to do really small videos, 5b can go as low as 128x128 but 2b wouldn't do it.

**Comment by cheezecrisp** [comment]
> Pretty sure 5b just supports more resolutions, noticed it before when trying to do really small videos, 5b can go as low as 128x128 but 2b wouldn't do it.

You're right, 720x480 is fine. The 2b version is very limited in resolution.
