### ISSUE TITLE
touchcompile didn't work

### ISSUE THREAD

**Issue by L020304** [kijai/ComfyUI-CogVideoXWrapper#296]
![小签](https://github.com/user-attachments/assets/6990ee0b-4384-4cec-8904-c20691b0e95d)

python 3.10.11
pythorch 2.5.0+cu124
triton-3.0.0-cp310-cp310-win_amd64

**Comment by willmiao** [comment]
Hi, I noticed that you closed this issue. I got the same error. How did you fix it? @L020304

**Comment by L020304** [comment]
![图片](https://github.com/user-attachments/assets/89f3aee7-b7a1-4e34-99d2-f5ecbb7f6b3e)
Turn off 'CPU Offload'
No fault indication, but the acceleration effect is not effective
