### ISSUE TITLE
IndexError: Dimension out of range (expected to be in range of [-4, 3], but got 4)

### ISSUE THREAD

**Issue by phr00t** [kijai/ComfyUI-CogVideoXWrapper#30]
![image](https://github.com/user-attachments/assets/641200c9-7989-42e7-a854-5af286a88903)

![image](https://github.com/user-attachments/assets/fd96dae9-990e-4087-907c-645b07d1fb4a)

EDIT: I've fixed the width/height/batch count to match the sampler, and I still get the same error.

There's no need to use the empty latens, the latent input is just for vid2vid, the comfy default latent format is incompatible as CogVideoX uses a 3D VAE.

**Comment by kijai** [comment]
Sorry accidentally edited your issue instead of replying 😅

**Comment by phr00t** [comment]
Ahh thank you, that's it!
