### ISSUE TITLE
cogvideox1.5-5b-prompt-camera-motion link is back online

### ISSUE THREAD

**Issue by AugmentedRealityCat** [kijai/ComfyUI-CogVideoXWrapper#301]
The cogvideox1.5-5b-prompt-camera-motion Lora from NimVideo is back online. The old link is working again, but it was not just an hour ago.

The only change I have spotted is that they now have a[ workflow example](https://huggingface.co/NimVideo/cogvideox1.5-5b-prompt-camera-motion/blob/main/cogvideox_1_5_5b_I2V_prompt_motion_lora_example.json) that was uploaded 6 hours ago, as well as more details and examples in the readme.

https://huggingface.co/NimVideo/cogvideox1.5-5b-prompt-camera-motion/tree/main

You can update the info cell in [the spreadsheet you have published](https://docs.google.com/spreadsheets/d/16eA6mSL8XkTcu9fSWkPSHfRIqyAKJbR1O99xnuGdCKY) to reflect that update.

**Comment by kijai** [comment]
Alright, thanks for letting me know!
