### ISSUE TITLE
no file named config.json found in directory

### ISSUE THREAD

**Issue by SlothDotEXE** [kijai/ComfyUI-CogVideoXWrapper#31]
When attempting to run the (first) workflow of example1.json, the output errors out before the 5b model can be downloaded. However, when running the 2b model it downloads and runs just fine.

![image](https://github.com/user-attachments/assets/e58e5279-233b-44b6-bff2-ab39df5b13ba)

**Comment by SlothDotEXE** [comment]
Issue resolved - Model had to be manually downloaded into the CogVideoX-5b directory.

**Comment by JioJe** [comment]
> 问题已解决 - 必须手动下载模型到 CogVideoX-5b 目录中。

您知道文件下载的地址吗？若能分享，感激不尽

**Comment by SlothDotEXE** [comment]
> > 问题已解决 - 必须手动下载模型到 CogVideoX-5b 目录中。
> 
> 您知道文件下载的地址吗？若能分享，感激不尽

https://huggingface.co/THUDM/CogVideoX-5b

Clone the entire repository into /ComfyUI/models/CogVideo/CogVideoX-5b and restart ComfyUI, it should work!

使用谷歌翻译
将整个存储库克隆到 /ComfyUI/models/CogVideo/CogVideoX-5b 并重新启动 ComfyUI，它应该可以工作了！
