### ISSUE TITLE
Node missing since last update: CogVideoXFunSampler

### ISSUE THREAD

**Issue by Persite007** [kijai/ComfyUI-CogVideoXWrapper#310]
I update ComfyUI and CogvideoXWrapper yesterday and since, **CogVideoXFunSampler node** is missing.
To check, I made a fresh ComfyUI portable install and add only CogvideoXWrapper custom node.
Same problem with CogVideoXFunSampler node
There is a soluce?

**Comment by kijai** [comment]
Yes, that node is removed, check the new example workflows. It's all explained under the Update8 in the readme.

**Comment by Persite007** [comment]
Thx u Kijai for fast reply. Ok I will check it.
Pity, because, I started to get good and relatively fast results with this node. Not easy on a RTX 3060 12Go...

https://github.com/user-attachments/assets/5b59361a-5478-4183-bb98-fd02da37c00f


https://github.com/user-attachments/assets/e41027ce-6049-4b37-92dd-9deb252ed922
