### ISSUE TITLE
'VAE' object has no attribute 'config'

### ISSUE THREAD

**Issue by suede299** [kijai/ComfyUI-CogVideoXWrapper#315]
# ComfyUI Error Report
## Error Details
- **Node ID:** 10
- **Node Type:** CogVideoImageEncode
- **Exception Type:** AttributeError
- **Exception Message:** 'VAE' object has no attribute 'config'
## Stack Trace
```
  File "H:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)

  File "H:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 244, in encode
    vae_scaling_factor = vae.config.scaling_factor
                         ^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.3.7-6-gac2f052
- **Arguments:** ComfyUI\main.py --cuda-malloc --bf16-vae --preview-method auto --use-pytorch-cross-attention --disable-xformers --port 7822 --extra-model-paths-config H:\StableSwarmUI\Data/comfy-auto-model.yaml --fast --preview-method latent2rgb
- **OS:** nt
- **Python Version:** 3.12.8 (tags/v3.12.8:2dc476b, Dec  3 2024, 19:30:04) [MSC v.1942 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25756696576
  - **VRAM Free:** 24110956544
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0
<img width="948" alt="{85229AC4-5475-425B-A7EE-23CDF9CA6421}" src="https://github.com/user-attachments/assets/13dea61a-c0ce-4ce7-ba93-904e434f3441">

**Comment by kijai** [comment]
Need to use the CogVideo VAE loader, the normal one won't work.

**Comment by suede299** [comment]
Okay. It worked.
