### ISSUE TITLE
redownload error

### ISSUE THREAD

**Issue by Codes4Fun** [kijai/ComfyUI-CogVideoXWrapper#336]
I update recently from an older version and the new one produced an error trying to download a model kijai/CogVideoX-Fun-5b I already had downloaded, I traced down the error to this line of code:

https://github.com/kijai/ComfyUI-CogVideoXWrapper/blob/main/model_loading.py#L219

it's currently written as:
```python
if not "1.1" and not "1.5" in model:
```

I think it was intended to be like this:
```python
if not "1.1" in model and not "1.5" in model:
```

that does fix it for me at least, not sure how many people would be impacted by the fix though, and I am not sure the download error was related or a hugging face repo issue.

**Comment by kijai** [comment]
You're right, that's mistake from me, fixed, thanks!
