### ISSUE TITLE
RuntimeError: mat1 and mat2 must have the same dtype, but got Float and BFloat16

### ISSUE THREAD

**Issue by vanche1212** [kijai/ComfyUI-CogVideoXWrapper#36]
![Uploading image.png…]()
torch == 2.4.0
RuntimeError: mat1 and mat2 must have the same dtype, but got Float and BFloat16

**Comment by vanche1212** [comment]
![image](https://github.com/user-attachments/assets/6930b0ff-6c06-4545-bab0-aa8e89725b8d)

**Comment by vanche1212** [comment]
I installed onediff and upgraded torch 2.4.0 according to the document, but the operation reported an error, parameter configuration, compile onediff

**Comment by kijai** [comment]
One of the recent commits accidentally broke onediff, should be fixed now, working for me again.

**Comment by vanche1212** [comment]
loc(callsite("/tmp/torchinductor_root/7t/c7ter5roc2a7wfwofdzl7vjxw72jrxjx3caeqys32evjbhee42a7.py":113:11 at "/tmp/torchinductor_root/7t/c7ter5roc2a7wfwofdzl7vjxw72jrxjx3caeqys32evjbhee42a7.py":358:28)): error: operation scheduled before its operands
loc(callsite("/tmp/torchinductor_root/wq/cwqkq47komkwp3ekncitjqirzkm52cgcz4mhvxsxgv7bhb3zlwap.py":125:11 at "/tmp/torchinductor_root/wq/cwqkq47komkwp3ekncitjqirzkm52cgcz4mhvxsxgv7bhb3zlwap.py":394:28)): error: operation scheduled before its operands
loc(callsite("/tmp/torchinductor_root/jz/cjz3v6dvdx5lcja756boil4qajoifjctn5qrijvbjnrfnlu5szfi.py":125:11 at "/tmp/torchinductor_root/jz/cjz3v6dvdx5lcja756boil4qajoifjctn5qrijvbjnrfnlu5szfi.py":394:28)): error: operation scheduled before its operands
loc(callsite("/tmp/torchinductor_root/6c/c6czanihrh72avurf2a53usebgaxhd7wn236notxnnkuscbsm5rc.py":113:11 at "/tmp/torchinductor_root/6c/c6czanihrh72avurf2a53usebgaxhd7wn236notxnnkuscbsm5rc.py":358:28)): error: operation scheduled before its operands
loc(callsite("/tmp/torchinductor_root/zi/cziz4fannlg3aoucnjhnrldyry3s3vyx6uz7sprmc7md76gykdmv.py":125:11 at "/tmp/torchinductor_root/zi/cziz4fannlg3aoucnjhnrldyry3s3vyx6uz7sprmc7md76gykdmv.py":394:28)): error: operation scheduled before its operands
^@AUTOTUNE nexfort_fused_attention(2x48x17776x64, 2x48x17776x64, 2x48x17776x64)
  triton_nexfort_fused_attention_3 121.8079 ms 100.0%
  triton_nexfort_fused_attention_1 126.0472 ms 96.6%
  triton_nexfort_fused_attention_2 132.3306 ms 92.0%
  triton_nexfort_fused_attention_4 158.1466 ms 77.0%
  triton_nexfort_fused_attention_0 308.6449 ms 39.5%
SingleProcess AUTOTUNE benchmarking takes 18.5451 seconds and 0.0003 seconds precompiling
W0904 21:27:41.912596 140694046832384 torch/fx/experimental/symbolic_shapes.py:4449] [0/1] xindex is not in var_ranges, defaulting to unknown range.
loc(callsite("/tmp/torchinductor_root/n3/cn3dnhmrecjkjmxxctj3lwjfdztssr7k2yewatb4ewst5jklqj3u.py":113:11 at "/tmp/torchinductor_root/n3/cn3dnhmrecjkjmxxctj3lwjfdztssr7k2yewatb4ewst5jklqj3u.py":358:28)): error: operation scheduled before its operands

I pulled the latest code, ran the same configuration as the above figure, and found an error, but it can run through. will this error affect the speed?

**Comment by kijai** [comment]
I've seen those before while it was still working. What kind of speed are you getting? I was able to get around 4.3 s/it when doing 49 frames at the default resolution on a 4090, someone else I know was able to get bit under 4s /it by first running the torch compile then switching to onediff, don't ask me why that would work but they do get those speeds.

**Comment by vanche1212** [comment]
<img width="1439" alt="截屏2024-09-04 21 48 31" src="https://github.com/user-attachments/assets/1e6e6132-b085-41a6-849d-e430a11d7ea4">
The speed has indeed increased, but the picture quality seems to have decreased by L. I wonder if onediff will affect the generated quality.  I don't know why 😄

**Comment by kijai** [comment]
> <img alt="截屏2024-09-04 21 48 31" width="1439" src="https://private-user-images.githubusercontent.com/19466281/364402795-1e6e6132-b085-41a6-849d-e430a11d7ea4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NTg0MTAsIm5iZiI6MTcyNTQ1ODExMCwicGF0aCI6Ii8xOTQ2NjI4MS8zNjQ0MDI3OTUtMWU2ZTYxMzItYjA4NS00MWE2LTg0OWQtZTQzMGExMWQ3ZWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDEzNTUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMTEyZmQ5ZjBiNzMzNWY5YmM0NzdkMDQzNjQ1MGZjOGU0N2U5OGRmMDc5OWI2MDA1ZjA2YmIyMjgxM2M5ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XNiAgNo-xZcHPSF13671LzljxX0IZdQhV2VP86dULcI"> The speed has indeed increased, but the picture quality seems to have decreased by L. I wonder if onediff will affect the generated quality. I don't know why 😄

It should not affect the quality much at all, from what we have tested it's 99% identical... if you get that high quality loss by just enabling it then something is still wrong.

**Comment by vanche1212** [comment]
> > <img alt="截屏2024-09-04 21 48 31" width="1439" src="https://private-user-images.githubusercontent.com/19466281/364402795-1e6e6132-b085-41a6-849d-e430a11d7ea4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NTg0MTAsIm5iZiI6MTcyNTQ1ODExMCwicGF0aCI6Ii8xOTQ2NjI4MS8zNjQ0MDI3OTUtMWU2ZTYxMzItYjA4NS00MWE2LTg0OWQtZTQzMGExMWQ3ZWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDEzNTUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwMTEyZmQ5ZjBiNzMzNWY5YmM0NzdkMDQzNjQ1MGZjOGU0N2U5OGRmMDc5OWI2MDA1ZjA2YmIyMjgxM2M5ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XNiAgNo-xZcHPSF13671LzljxX0IZdQhV2VP86dULcI"> The speed has indeed increased, but the picture quality seems to have decreased by L. I wonder if onediff will affect the generated quality. I don't know why 😄
> 
> It should not affect the quality much at all, from what we have tested it's 99% identical... if you get that high quality loss by just enabling it then something is still wrong.

yes，I'll try again, thanks
