### ISSUE TITLE
Any example json file of generating endless videos?

### ISSUE THREAD

**Issue by dogecoinvr** [kijai/ComfyUI-CogVideoXWrapper#38]

**Comment by TemporalLabsLLC-SOL** [comment]
Yeah. I made this and changed it so, if you have the power, you just type in the desired end length.

[WORKFLOW LINK](https://openart.ai/workflows/sol_temporallabsllc/temporal-labs-llc-presents-cogvideo5b-infinity-study-6-second-generations/Uh4tTacq0UiYHdMjgk3P)

`SYSTEM SPECIFICATIONS
Python Version:

Python 3.10.14

GPU Information:

Mon Sep  2 05:53:16 2024      

+---------------------------------------------------------------------------------------+

| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |

|-----------------------------------------+----------------------+----------------------+

| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |

| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |

|                                         |                      |               MIG M. |

|=========================================+======================+======================|

|   0  NVIDIA L40S                    On  | 00000000:34:00.0 Off |                    0 |

| N/A   39C    P0              79W / 350W |  17113MiB / 46068MiB |      0%      Default |

|                                         |                      |                  N/A |

+-----------------------------------------+----------------------+----------------------+

                                                                                       

+---------------------------------------------------------------------------------------+

| Processes:                                                                            |

|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |

|        ID   ID                                                             Usage      |

|=======================================================================================|

|    0   N/A  N/A      2389      C   ...ubuntu/venvs/comfyui_env/bin/python    17100MiB |

+---------------------------------------------------------------------------------------+`
