### ISSUE TITLE
IMPORT FAILED

### ISSUE THREAD

**Issue by gghuanhuan** [kijai/ComfyUI-CogVideoXWrapper#39]
`(IMPORT FAILED): D:\softwares\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-CogVideoXWrapper`

Why did I still fail to import node despite installing the required libraries
`Package                   Version
------------------------- ------------------
accelerate                0.33.0
aiofiles                  23.2.1
aiohappyeyeballs          2.3.4
aiohttp                   3.10.0
aiosignal                 1.3.1
albucore                  0.0.13
albumentations            1.4.12
altair                    5.4.1
annotated-types           0.7.0
antlr4-python3-runtime    4.9.3
anyio                     4.4.0
async-timeout             4.0.3
attrs                     23.2.0
av                        12.3.0
bitsandbytes              0.43.3
blinker                   1.8.2
boto3                     1.34.86
botocore                  1.34.162
cachetools                5.5.0
certifi                   2024.7.4
cffi                      1.16.0
cfgv                      3.4.0
chardet                   5.2.0
charset-normalizer        3.3.2
cheroot                   10.0.1
click                     8.1.7
cloudpickle               3.0.0
colorama                  0.4.6
contourpy                 1.2.1
cycler                    0.12.1
Cython                    3.0.10
decorator                 4.4.2
deepdiff                  8.0.0
diffusers                 0.30.1
distlib                   0.3.8
distro                    1.9.0
dynamicprompts            0.31.0
easydict                  1.13
einops                    0.8.0
eval_type_backport        0.2.0
exceptiongroup            1.2.2
facexlib                  0.3.0
fastapi                   0.112.1
ffmpy                     0.4.0
filelock                  3.15.4
filterpy                  0.0.15
fonttools                 4.53.1
frozenlist                1.4.1
fsspec                    2024.6.1
fvcore                    0.1.5.post20221221
gevent                    24.2.1
gitdb                     4.0.11
GitPython                 3.1.43
gradio                    4.42.0
gradio_client             1.3.0
greenlet                  3.0.3
h11                       0.14.0
HTMLParser                0.0.2
httpcore                  1.0.5
httpx                     0.27.0
huggingface-hub           0.24.6
identify                  2.6.0
idna                      3.7
imageio                   2.34.2
imageio-ffmpeg            0.5.1
importlib_metadata        8.2.0
importlib_resources       6.4.0
insightface               0.7.3
iopath                    0.1.9
jaraco.functools          4.0.1
Jinja2                    3.1.4
jiter                     0.5.0
jmespath                  1.0.1
joblib                    1.4.2
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
lazy_loader               0.4
linkai                    0.0.6.0
llvmlite                  0.43.0
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.9.1
mdurl                     0.1.2
more-itertools            10.3.0
moviepy                   1.0.3
mpmath                    1.3.0
multidict                 6.0.5
narwhals                  1.5.5
networkx                  3.2.1
nodeenv                   1.9.1
numba                     0.60.0
numpy                     1.26.4
onnx                      1.16.2
openai                    1.42.0
opencv-python             4.10.0.84
opencv-python-headless    4.10.0.84
orderly-set               5.2.1
orjson                    3.10.7
packaging                 24.1
pandas                    2.2.2
pillow                    10.4.0
pip                       22.0.4
platformdirs              4.2.2
portalocker               2.10.1
pre-commit                3.8.0
prettytable               3.10.2
proglog                   0.1.10
protobuf                  5.27.3
psutil                    6.0.0
py-cpuinfo                9.0.0
pyarrow                   17.0.0
pycparser                 2.22
pydantic                  2.8.2
pydantic_core             2.20.1
pydeck                    0.9.1
pydub                     0.25.1
Pygments                  2.18.0
pynvml                    11.5.3
pyparsing                 3.1.2
pypng                     0.20220715.0
PyQRCode                  1.2.1
python-dateutil           2.9.0.post0
python-multipart          0.0.9
pytz                      2024.1
pywin32                   306
PyYAML                    6.0.1
qrcode                    7.4.2
referencing               0.35.1
regex                     2024.7.24
requests                  2.32.3
requests-toolbelt         1.0.0
rich                      13.7.1
rpds-py                   0.20.0
ruff                      0.6.1
s3transfer                0.10.2
safetensors               0.4.4
scikit-image              0.24.0
scikit-learn              1.5.1
scipy                     1.13.1
semantic-version          2.10.0
sentencepiece             0.2.0
setuptools                58.1.0
shellingham               1.5.4
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.1
starlette                 0.38.2
streamlit                 1.38.0
surrealist                0.5.3
SwissArmyTransformer      0.4.12
sympy                     1.13.1
tabulate                  0.9.0
tenacity                  8.5.0
termcolor                 2.4.0
threadpoolctl             3.5.0
tifffile                  2024.7.24
tiktoken                  0.7.0
timm                      0.6.13
tokenizers                0.19.1
toml                      0.10.2
tomli                     2.0.1
tomlkit                   0.12.0
torch                     2.4.0+cu124
torchvision               0.19.0+cu124
tornado                   6.4.1
tqdm                      4.66.4
transformers              4.44.0
typer                     0.12.4
typing_extensions         4.12.2
tzdata                    2024.1
urllib3                   2.2.2
uvicorn                   0.30.6
virtualenv                20.26.3
watchdog                  4.0.2
wcwidth                   0.2.13
web.py                    0.62
websocket-client          1.8.0
websockets                12.0
yacs                      0.1.8
yarl                      1.9.4
zipp                      3.19.2
zope.event                5.0
zope.interface            6.4.post2`

**Comment by kijai** [comment]
The startup logging in comfy should report it somewhere there, usually something like "module not found" .

**Comment by KewkLW** [comment]
It could be so many things, should prolly post your comfyui.log. Tho, I was having an issue and reinstalled xformers to fix it >__<

**Comment by gghuanhuan** [comment]
> The startup logging in comfy should report it somewhere there, usually something like "module not found" .

I have reinstalled the Torch and xformers libraries and can now import nodes normally. Thank you
`[2024-09-02 22:46] Traceback (most recent call last):
  File "D:\softwares\ComfyUI-aki-v1.3\python\lib\site-packages\xformers\checkpoint.py", line 53, in <module>
    from torch.utils.checkpoint import SAC_IGNORED_OPS as _ignored_ops  # type: ignore
ImportError: cannot import name 'SAC_IGNORED_OPS' from 'torch.utils.checkpoint' (D:\softwares\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\checkpoint.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\softwares\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\utils\import_utils.py", line 830, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "D:\softwares\ComfyUI-aki-v1.3\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\softwares\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\models\autoencoders\__init__.py", line 1, in <module>
    from .autoencoder_asym_kl import AsymmetricAutoencoderKL
  File "D:\softwares\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\models\autoencoders\autoencoder_asym_kl.py", line 23, in <module>
    from .vae import DecoderOutput, DiagonalGaussianDistribution, Encoder, MaskConditionDecoder
  File "D:\softwares\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\models\autoencoders\vae.py", line 24, in <module>
    from ..attention_processor import SpatialNorm
  File "D:\softwares\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\models\attention_processor.py", line 34, in <module>
    import xformers
  File "D:\softwares\ComfyUI-aki-v1.3\python\lib\site-packages\xformers\__init__.py", line 12, in <module>
    from .checkpoint import (  # noqa: E402, F401
  File "D:\softwares\ComfyUI-aki-v1.3\python\lib\site-packages\xformers\checkpoint.py", line 57, in <module>
    from torch.utils.checkpoint import _ignored_ops  # type: ignore
ImportError: cannot import name '_ignored_ops' from 'torch.utils.checkpoint' (D:\softwares\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\checkpoint.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\softwares\ComfyUI-aki-v1.3\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\softwares\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-CogVideoXWrapper\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\softwares\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 7, in <module>
    from diffusers.models import AutoencoderKLCogVideoX, CogVideoXTransformer3DModel
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\softwares\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\utils\import_utils.py", line 820, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\softwares\ComfyUI-aki-v1.3\python\lib\site-packages\diffusers\utils\import_utils.py", line 832, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.models.autoencoders.autoencoder_kl_cogvideox because of the following error (look up to see its traceback):
cannot import name '_ignored_ops' from 'torch.utils.checkpoint' (D:\softwares\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\checkpoint.py)

[2024-09-02 22:46] Cannot import D:\softwares\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-CogVideoXWrapper module for custom nodes: Failed to import diffusers.models.autoencoders.autoencoder_kl_cogvideox because of the following error (look up to see its traceback):
cannot import name '_ignored_ops' from 'torch.utils.checkpoint' (D:\softwares\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\checkpoint.py)
`

**Comment by gghuanhuan** [comment]
> It could be so many things, should prolly post your comfyui.log. Tho, I was having an issue and reinstalled xformers to fix it >__<

You're right, thank you for your help
