### ISSUE TITLE
RuntimeError: torch._scaled_mm is only supported on CUDA devices with compute capability >= 9.0 or 8.9, or ROCm MI300+

### ISSUE THREAD

**Issue by Fictiverse** [kijai/ComfyUI-CogVideoXWrapper#40]
Hi here, i tryed to test CogVideoX with an RTX 3090. But when i launch i got this error message :

`RuntimeError: torch._scaled_mm is only supported on CUDA devices with compute capability >= 9.0 or 8.9, or ROCm MI300+`

**Comment by ywaby** [comment]
fp8 fast mode will cause this problem
