### ISSUE TITLE
LCM support

### ISSUE THREAD

**Issue by MGTRIDER** [kijai/ComfyUI-CogVideoXWrapper#41]
Hi there sir, is it possible to add the LCM sampler as an alternative sampler for faster convergence, thereby speeding up rendering? And maybe even something like HyperTile. But i think that LCM sampler support would already give a big boost. Thank you for your time.

**Comment by kijai** [comment]
The LCM sampler itself is not faster, it's just the sampling method needed to sample LCM distilled models, and there's nothing like that available for CogVideoX.

**Comment by MGTRIDER** [comment]
> The LCM sampler itself is not faster, it's just the sampling method needed to sample LCM distilled models, and there's nothing like that available for CogVideoX.

I see, thanks for the explanation. Can you help me with the following issue ? Whenever i try to use the fp8 transformer on the CogVideo 2b model, i get the following error: Promotion for Float8 Types is not supported, attempted to promote Half and Float8_e4m3fn

**Comment by kijai** [comment]
> > The LCM sampler itself is not faster, it's just the sampling method needed to sample LCM distilled models, and there's nothing like that available for CogVideoX.
> 
> I see, thanks for the explanation. Can you help me with the following issue ? Whenever i try to use the fp8 transformer on the CogVideo 2b model, i get the following error: Promotion for Float8 Types is not supported, attempted to promote Half and Float8_e4m3fn

It's not currently supported on the 2b model, there's a workaround but I haven't applied it yet.

**Comment by MGTRIDER** [comment]
> > > The LCM sampler itself is not faster, it's just the sampling method needed to sample LCM distilled models, and there's nothing like that available for CogVideoX.
> > 
> > 
> > I see, thanks for the explanation. Can you help me with the following issue ? Whenever i try to use the fp8 transformer on the CogVideo 2b model, i get the following error: Promotion for Float8 Types is not supported, attempted to promote Half and Float8_e4m3fn
> 
> It's not currently supported on the 2b model, there's a workaround but I haven't applied it yet.

Alright, thank you very much, then i will close the issue.

**Comment by kijai** [comment]
> > The LCM sampler itself is not faster, it's just the sampling method needed to sample LCM distilled models, and there's nothing like that available for CogVideoX.
> 
> I see, thanks for the explanation. Can you help me with the following issue ? Whenever i try to use the fp8 transformer on the CogVideo 2b model, i get the following error: Promotion for Float8 Types is not supported, attempted to promote Half and Float8_e4m3fn

Using fp8 with the 2b model should now be working.
