### ISSUE TITLE
wrong filename

### ISSUE THREAD

**Issue by Willian7004** [kijai/ComfyUI-CogVideoXWrapper#45]
I downloaded THUDM/CogVideoX-5b from huggingface but the program stopped with error Error no file named diffusion_pytorch_model.bin found in directory D:\ComfyUI-aki-v1.3\models\CogVideo\CogVideoX-5b. .However,the model I downloaded was named diffusion_pytorch_model-00001-of-00002.safetensors and diffusion_pytorch_model-00002-of-00002.safetensors .

**Comment by kijai** [comment]
Yes those what you downloaded are right, the error about `diffusion_pytorch_model.bin` is a generic one diffusers seems to always give when it can't find the model. Check that the folder structure matches what's on huggingface, and check that all the .json files are there and with same names, as they are also required.

**Comment by Willian7004** [comment]
I checked the filenamed again and found that I downloaded the files from browser and all files names was added the folder name as a perfix to avoid duplicate file names.I changed the filenames and it works.

**Comment by kijai** [comment]
Yeah and huggingface seems to always add the subfolder to the filename with .json's.
