### ISSUE TITLE
CogVideoXPipeline.__call__() got an unexpected keyword argument 'scheduler_name'

### ISSUE THREAD

**Issue by sipie800** [kijai/ComfyUI-CogVideoXWrapper#46]
use ComfyUI-CogVideoXWrapper and this repo in comfyui.

The code shows that there is 'scheduler_name' in the __call__ method actually, very confusing.

**Comment by kijai** [comment]
Yeah that doesn't make sense, what's the full error?

**Comment by sipie800** [comment]
the problem is fixed by updating **accelerate** to newest.
