### ISSUE TITLE
CogVideoTextEncode： 'SD1Tokenizer' object has no attribute 't5xxl' 

### ISSUE THREAD

**Issue by aetherwu** [kijai/ComfyUI-CogVideoXWrapper#52]
File "/home/user/app/custom_nodes/ComfyUI-CogVideoXWrapper/nodes.py", line 169, in process
    clip.tokenizer.t5xxl.pad_to_max_length = True
AttributeError: 'SD1Tokenizer' object has no attribute 't5xxl'

Is this caused by worng t5 model?
I used one from:
https://huggingface.co/JulesGo/t5-v1_1-xxl-fp8_text_encoder_2

**Comment by CambridgeComputing** [comment]
Can you post your workflow (either a good screenshot or the `json`)? The fact that it's mentioning SD1 in the error makes me suspect that you have the wrong `type` selected in the `Load CLIP` node (should be `SD3`).

**Comment by Sirachosur** [comment]
@aetherwu Hi, please check your 'Load CLIP' node and make sure you have a t5xxl selected as clip_name.  I had the same error message as you and that's how I fixed it.
![image](https://github.com/user-attachments/assets/f27de0e9-12ab-4631-b516-1c721cdcbeac)

**Comment by TRONBFFL** [comment]
I have this error and I am using t5xxl_fp8_e4m3fn.safetensors 

<img width="580" alt="image" src="https://github.com/user-attachments/assets/f39dd6a7-d43e-4f6e-9f60-daf1e474d429">

**Comment by kijai** [comment]
> I have this error and I am using t5xxl_fp8_e4m3fn.safetensors 
> 
> <img width="580" alt="image" src="https://github.com/user-attachments/assets/f39dd6a7-d43e-4f6e-9f60-daf1e474d429">
> 

Gotta select SD3 as the model type for the clip loader
