### ISSUE TITLE
Image to video

### ISSUE THREAD

**Issue by SanicsP** [kijai/ComfyUI-CogVideoXWrapper#6]
Hello , I saw that you have integrated a video to video workflow, as for the image to video generation, I would be interested for some indications on how to do the workflow

**Comment by bertagknowles** [comment]
I too am interested in Image to video so that we can give it a starting frame just like kling and the results would be cool!

**Comment by kijai** [comment]
The model itself does not support image2video, nothing to be done unless they release different model.
