### ISSUE TITLE
RuntimeError: The size of tensor a (90) must match the size of tensor b (60) at non-singleton dimension 4

### ISSUE THREAD

**Issue by rrroddri** [kijai/ComfyUI-CogVideoXWrapper#60]
Hi, thank you for everything you're doing, i'm trying to test the new img2video model but no matter what resolution I try, I always get the same error:

![cogerror](https://github.com/user-attachments/assets/a7c07298-1e23-4a51-b338-592385e342f4)

`final latents:  torch.Size([1, 1, 16, 60, 90])
!!! Exception during processing !!! The size of tensor a (90) must match the size of tensor b (60) at non-singleton dimension 4
Traceback (most recent call last):
  File "G:\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "G:\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "G:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "G:\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 352, in process
    latents = pipeline["pipe"](
  File "G:\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "G:\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\pipeline_cogvideox.py", line 431, in __call__
    latents, timesteps, noise = self.prepare_latents(
  File "G:\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\pipeline_cogvideox.py", line 192, in prepare_latents
    latents = self.scheduler.add_noise(latents, noise, latent_timestep)
  File "G:\ComfyUI\venv\lib\site-packages\diffusers\schedulers\scheduling_ddim_cogvideox.py", line 425, in add_noise
    noisy_samples = sqrt_alpha_prod * original_samples + sqrt_one_minus_alpha_prod * noise
RuntimeError: The size of tensor a (90) must match the size of tensor b (60) at non-singleton dimension 4

Prompt executed in 0.96 seconds`

Thank you in advance

**Comment by kijai** [comment]
It's still work in progress, but I've managed to run it succesfully already. You need to input the image to the "image_cond_latents", I don't know yet if this can work with the other latent input, which is meant for vid2vid instead.

**Comment by rrroddri** [comment]
Thanks, I'm using the workflow you updated, it kinda works but now it gives me another error, oh well at least the cogxvideofun works

`!!! Exception during processing !!! It is currently not possible to generate videos at a different resolution that the defaults. This should only be the case with 'THUDM/CogVideoX-5b-I2V'.If you think this is incorrect, please open an issue at https://github.com/huggingface/diffusers/issues.
Traceback (most recent call last):
  File "G:\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "G:\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "G:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "G:\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 352, in process
    latents = pipeline["pipe"](
  File "G:\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "G:\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\pipeline_cogvideox.py", line 616, in __call__
    noise_pred = self.transformer(
  File "G:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "G:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\ComfyUI\venv\lib\site-packages\diffusers\models\transformers\cogvideox_transformer_3d.py", line 429, in forward
    hidden_states = self.patch_embed(encoder_hidden_states, hidden_states)
  File "G:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "G:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\ComfyUI\venv\lib\site-packages\diffusers\models\embeddings.py", line 423, in forward
    raise ValueError(
ValueError: It is currently not possible to generate videos at a different resolution that the defaults. This should only be the case with 'THUDM/CogVideoX-5b-I2V'.If you think this is incorrect, please open an issue at https://github.com/huggingface/diffusers/issues.`

**Comment by CambridgeComputing** [comment]
> Thanks, I'm using the workflow you updated, it kinda works but now it gives me another error, oh well at least the cogxvideofun works
> 
> `!!! Exception during processing !!! It is currently not possible to generate videos at a different resolution that the defaults. This should only be the case with 'THUDM/CogVideoX-5b-I2V'.If you think this is incorrect, please open an issue at https://github.com/huggingface/diffusers/issues. Traceback (most recent call last): File "G:\ComfyUI\execution.py", line 323, in execute output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) File "G:\ComfyUI\execution.py", line 198, in get_output_data return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) File "G:\ComfyUI\execution.py", line 169, in _map_node_over_list process_inputs(input_dict, i) File "G:\ComfyUI\execution.py", line 158, in process_inputs results.append(getattr(obj, func)(**inputs)) File "G:\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 352, in process latents = pipeline["pipe"]( File "G:\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context return func(*args, **kwargs) File "G:\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\pipeline_cogvideox.py", line 616, in __call__ noise_pred = self.transformer( File "G:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "G:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl return forward_call(*args, **kwargs) File "G:\ComfyUI\venv\lib\site-packages\diffusers\models\transformers\cogvideox_transformer_3d.py", line 429, in forward hidden_states = self.patch_embed(encoder_hidden_states, hidden_states) File "G:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "G:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl return forward_call(*args, **kwargs) File "G:\ComfyUI\venv\lib\site-packages\diffusers\models\embeddings.py", line 423, in forward raise ValueError( ValueError: It is currently not possible to generate videos at a different resolution that the defaults. This should only be the case with 'THUDM/CogVideoX-5b-I2V'.If you think this is incorrect, please open an issue at https://github.com/huggingface/diffusers/issues.`

Is your input image exactly 720x480? I believe that the image must be that size and that the sampler has the same (480 height, 720 width).

**Comment by rrroddri** [comment]
@CambridgeComputing yeah, it seems the THUDM i2v model is resolution locked while the CogXVideo-fun one isn't

**Comment by Ratinod** [comment]
@rrroddri 
Can you test it with 360x240 image? And how much VRAM will be consumed in this case?
