### ISSUE TITLE
Feature request: saving/loading latents after sampling

### ISSUE THREAD

**Issue by tavyscrolls** [kijai/ComfyUI-CogVideoXWrapper#64]
Using the inbuilt save/load latent with vae tiling enabled results in the error:

`Could not run 'aten::slow_conv3d_forward' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee `

And with vae tiling off:

`Sizes of tensors must match except in dimension 2. Expected size 60 but got size 12 for tensor number 1 in the list.`

Would be super useful to have a smaller GPU sampling videos while 30/4090 does the decoding and interpolation stuff, assuming this isn't a comfy limitation. Or even just saving a couple minutes of sampling because OOM in the final stretch

**Comment by synystersocks** [comment]
after the first generation i get with vae tiling on - Sizes of tensors must match except in dimension 1. Expected size 60 but got size 65 for tensor number 4 in the list.

if you restart comfyui fully so it unloads out of your ram, and go back in, that seems to fix the issue for that generation "if both issues are related". im guessing something is being partially passed into the latent value, possibly from keeping some of the previouly used data from the 1st generation or just that specific latent var that isnt resetting correctly.

unloading the model alone doesnt seem to work, only a full restart of comfyui.

**Comment by kijai** [comment]
These issues should be resolved by now, also it is possible to use the built in Save/Load latent node with this.
