### ISSUE TITLE
Neon grid result - Temporal tiling disabled?

### ISSUE THREAD

**Issue by rhystz** [kijai/ComfyUI-CogVideoXWrapper#65]
Hi Kijai, Thanks heaps for everything you do. I'm getting a gridded output (16 frames, otherwise same as example workflow settings) and a few inconsistently appearing msgs:

torch.Size([1, 4, 16, 60, 90])
tensor(0.) tensor(1.)
[VideoHelperSuite] - WARNING - Output images were not of valid resolution and have had padding applied
Prompt executed in 549.20 seconds
[Crystools ERROR] For some reason, pynvml is not working in a laptop with only battery, try to connect and turn on the monitor ** not always there**
[Crystools ERROR] Monitor of GPU is turning off (not on UI!) ** not always there**
got prompt
latents torch.Size([1, 8, 16, 60, 90])
Temporal tiling disabled
latents.shape torch.Size([1, 8, 16, 60, 90])

I've hit OOMs a couple of times but seem to be able to move forward straight afterwards. im on a laptop rtx a4500. Do you know what could be causing it? Non-I2V 5b model runs well.
 
![image](https://github.com/user-attachments/assets/57a11e77-705e-48d5-a434-5b9ebc2a208d)

**Comment by rhystz** [comment]
I also couldn't get the down(load) and load cog model node to work so just git cloned from thud into models/cogvideo

**Comment by rhystz** [comment]
The result is good on 49 frames.

**Comment by tdrminglin** [comment]
I also get grid results,

**Comment by kijai** [comment]
I think the I2V model simply only works with 49 frames, those are the results with other frame amounts I've tried as well.

**Comment by rhystz** [comment]
Ahh ok great, thanks.
