### ISSUE TITLE
CogVideoX-5b-I2V

### ISSUE THREAD

**Issue by Cal-DCosta** [kijai/ComfyUI-CogVideoXWrapper#67]

**Comment by rhystz** [comment]
I had the same issue with no auto download, but as far as i can tell cloning the hugging face i2v folder into models/CogVideo worked for me

**Comment by nnimoyoefoki** [comment]
This might help:This file might fix it
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
If you don't have the c compliator, install it.(gcc or clang)
