### ISSUE TITLE
does not have a parameter or a buffer named pos_embedding.

### ISSUE THREAD

**Issue by huanggou666** [kijai/ComfyUI-CogVideoXWrapper#68]
DownloadAndLoadCogVideoModel
CogVideoXPatchEmbed( (proj): Conv2d(32, 3072, kernel_size=(2, 2), stride=(2, 2)) (text_proj): Linear(in_features=4096, out_features=3072, bias=True) ) does not have a parameter or a buffer named pos_embedding.
![image](https://github.com/user-attachments/assets/ac9772f1-ab88-4b85-baed-c1483e638f3e)

**Comment by kijai** [comment]
You need to update diffusers to 0.30.3

**Comment by huanggou666** [comment]
> You need to update diffusers to 0.30.3

Thanks , problem solved
