### ISSUE TITLE
The size of tensor a (18002) must match the size of tensor b (17776) at non-singleton dimension 1

### ISSUE THREAD

**Issue by huanggou666** [kijai/ComfyUI-CogVideoXWrapper#72]
The size of tensor a (18002) must match the size of tensor b (17776) at non-singleton dimension 1
![image](https://github.com/user-attachments/assets/dd3b0bb8-6933-492b-ad79-5cbe07dbf51d)

**Comment by huanggou666** [comment]
closed

**Comment by pyoliu** [comment]
Has it been resolved? I also encountered this problem

**Comment by huanggou666** [comment]
> Has it been resolved? I also encountered this problem

keep the prompt text shorter solved my problem
