### ISSUE TITLE
The size of tensor a (18002) must match the size of tensor b (17776) at non-singleton dimension 1

### ISSUE THREAD

**Issue by pyoliu** [kijai/ComfyUI-CogVideoXWrapper#73]
I successfully generated the image for the video before, but when I changed the image, an error occurred. Since then, I have been continuously reporting errors and have not changed the parameters
![Snipaste_2024-09-20_13-56-19](https://github.com/user-attachments/assets/25e689d0-aa59-4643-a645-e1848bc4938e)

**Comment by nieli123456** [comment]
同样的报错

**Comment by pyoliu** [comment]
> 同样的报错

是不是提示词太长了，我太长就报错，缩短了就没事了
