### ISSUE TITLE
help me：“TypeError: CogVideoXPipeline.__call__() got an unexpected keyword argument 'video'”

### ISSUE THREAD

**Issue by tiandaoyuxi** [kijai/ComfyUI-CogVideoXWrapper#74]
!!! Exception during processing !!! 'Unfun' models not supported in 'CogVideoXFunSampler', use the 'CogVideoSampler'
Traceback (most recent call last):
  File "D:\Comfy_UI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\Comfy_UI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfy_UI\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\nodes.py", line 594, in process
    assert "Fun" in base_path, "'Unfun' models not supported in 'CogVideoXFunSampler', use the 'CogVideoSampler'"
           ^^^^^^^^^^^^^^^^^^
AssertionError: 'Unfun' models not supported in 'CogVideoXFunSampler', use the 'CogVideoSampler'

**Comment by MayoPonyo** [comment]
I have the same issue. It worked first try. Then out of the blue it stopped. Restarting COmfyUi did not solve my problem.
