### ISSUE TITLE
Failed import

### ISSUE THREAD

**Issue by AmigoBarba** [kijai/ComfyUI-CogVideoXWrapper#76]
Hi all,
I installed ComfyUI and with the Mod Manager I tried to install the CogVideoXWrapper, but it doesn't work.
I does create the folders and files but in Mod Manager I get this, when I try to "fix it":
Install: ['https://github.com/kijai/ComfyUI-CogVideoXWrapper']
Download: git clone 'https://github.com/kijai/ComfyUI-CogVideoXWrapper'
[!]
 Cmd('git') failed due to: exit code(128)
0it [00:00, ?it/s]  cmdline: git clone -v --recursive --progress -- https://github.com/kijai/ComfyUI-CogVideoXWrapper E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper

Also, when I put an example workflow in ComfyUI, I get this:
Warning: Missing Node Types

When loading the graph, the following node types were not found:

    CogVideoTextEncode
    CogVideoSampler
    DownloadAndLoadCogVideoModel
    CogVideoDecode

How can I fix this?

**Comment by Hypothyroidism** [comment]
I have the exact same issue right now.

**Comment by Batuking1111** [comment]
same

**Comment by kijai** [comment]
Look for import errors in the startup log, "module not found" or something. Most likely it's wrong diffusers version, it needs to be the latest one 0.30.3

**Comment by Batuking1111** [comment]
How to update diffusers in windows?

**Comment by AmigoBarba** [comment]
It says I don't have Imagio, but upon trying to install it, it says the already installed.
"import imageio
ModuleNotFoundError: No module named 'imageio'

Cannot import E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper module for custom nodes: No module named 'imageio'"

Tried:
pip install imageio
pip install imageio[ffmpeg]
pip install imageio[pyav]
pip install openpiv --upgrade --force-reinstall

What should I do?

**Comment by kijai** [comment]
> It says I don't have Imagio, but upon trying to install it, it says the already installed. "import imageio ModuleNotFoundError: No module named 'imageio'
> 
> Cannot import E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper module for custom nodes: No module named 'imageio'"
> 
> Tried: pip install imageio pip install imageio[ffmpeg] pip install imageio[pyav] pip install openpiv --upgrade --force-reinstall
> 
> What should I do?

Right, imageio as requirement was accidentally included from the CogVideoX-Fun code... removed it now so it's not needed any longer.

**Comment by kijai** [comment]
> How to update diffusers in windows?

You would go to your `ComfyUI_windows_portable\python_embeded` -folder and run this command:

`python.exe -m pip install -U diffusers`

**Comment by ricklove** [comment]
Updating diffusers fixed it for me

**Comment by alastaira** [comment]
Just encountered the same problem. Updating diffusers suggests I was already using the latest versions:

```
Requirement already satisfied: diffusers in c:\comfyui_windows_portable_nvidia\comfyui_windows_portable\python_embeded\lib\site-packages (0.30.3)
Requirement already satisfied: importlib-metadata in c:\comfyui_windows_portable_nvidia\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers) (8.5.0)
Requirement already satisfied: filelock in c:\comfyui_windows_portable_nvidia\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers) (3.15.4)
Requirement already satisfied: huggingface-hub>=0.23.2 in c:\comfyui_windows_portable_nvidia\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers) (0.24.2)
Requirement already satisfied: numpy in c:\comfyui_windows_portable_nvidia\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers) (1.26.4)
Requirement already satisfied: regex!=2019.12.17 in c:\comfyui_windows_portable_nvidia\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers) (2024.7.24)
Requirement already satisfied: requests in c:\comfyui_windows_portable_nvidia\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers) (2.32.3)
Requirement already satisfied: safetensors>=0.3.1 in c:\comfyui_windows_portable_nvidia\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers) (0.4.3)
Requirement already satisfied: Pillow in c:\comfyui_windows_portable_nvidia\comfyui_windows_portable\python_embeded\lib\site-packages (from diffusers) (10.4.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\comfyui_windows_portable_nvidia\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub>=0.23.2->diffusers) (2024.6.1)
Requirement already satisfied: packaging>=20.9 in c:\comfyui_windows_portable_nvidia\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub>=0.23.2->diffusers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\comfyui_windows_portable_nvidia\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub>=0.23.2->diffusers) (6.0.1)
Requirement already satisfied: tqdm>=4.42.1 in c:\comfyui_windows_portable_nvidia\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub>=0.23.2->diffusers) (4.66.4)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\comfyui_windows_portable_nvidia\comfyui_windows_portable\python_embeded\lib\site-packages (from huggingface-hub>=0.23.2->diffusers) (4.12.2)
Requirement already satisfied: zipp>=3.20 in c:\comfyui_windows_portable_nvidia\comfyui_windows_portable\python_embeded\lib\site-packages (from importlib-metadata->diffusers) (3.20.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\comfyui_windows_portable_nvidia\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->diffusers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\comfyui_windows_portable_nvidia\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->diffusers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\comfyui_windows_portable_nvidia\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->diffusers) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in c:\comfyui_windows_portable_nvidia\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->diffusers) (2024.7.4)
Requirement already satisfied: colorama in c:\comfyui_windows_portable_nvidia\comfyui_windows_portable\python_embeded\lib\site-packages (from tqdm>=4.42.1->huggingface-hub>=0.23.2->diffusers) (0.4.6)
```

**Comment by AmigoBarba** [comment]
Updating/reinstalling everything everywhere basically fixed it for me, but this is not really user friendly at all.
However when trying to do a video from an example workflow, it runs and GPU works like crazy, but then it gave error messages at the end, I don't even know where this was supposed to save the output video?

I hope someone will come up with an user friendly GUI to handle this, I just want to animate personal images.

**Comment by alastaira** [comment]
Well, I've uninstalled, reinstalled, and updated every possible dependency I can think of (and broke my existing Flux workflow in the process..... guess I should have tried this in an isolated venv!). Might have to wait until it's a little more stable I guess!

**Comment by kijai** [comment]
> Well, I've uninstalled, reinstalled, and updated every possible dependency I can think of (and broke my existing Flux workflow in the process..... guess I should have tried this in an isolated venv!). Might have to wait until it's a little more stable I guess!

There really isn't that many requirements, mostly just diffusers and accelerate... none of that should break anything Flux related.

There was however extra dependency accidentally added that I didn't have in requirements, which could be your issue as well, updating the nodes now should solve that one. If it still can't import, then please post your ComfyUI startup log so we can see which dependency is the culprit, always possible I've missed some.

**Comment by alastaira** [comment]
Many thanks for replying so quickly. Looking at the log, the error I'm getting is:
```
"C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper\videosys\modules\embeddings.py", line 11, in <module>
    from timm.models.vision_transformer import Mlp
ModuleNotFoundError: No module named 'timm'
```

**Comment by alastaira** [comment]
I can do a `pip install timm` but should that already be in the requirements.txt?

**Comment by kijai** [comment]
> I can do a `pip install timm` but should that already be in the requirements.txt?
>  

It was already removed as requirement, latest version of the nodes do not try to import it at all.

**Comment by alastaira** [comment]
Thankyou again! Ok, so after another update/refresh cycle, I now have the custom nodes appearing correctly!

But attempting to queue the example workflows now gives errors:

If I select the 2b model, I get:
```
Error no file named diffusion_pytorch_model.bin found in directory C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\CogVideo\CogVideo2B.
```

Whereas if I select the 5b model instead:
```
ValueError: C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\CogVideo\CogVideoX-5b\transformer does not appear to have a file named C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\CogVideo\CogVideoX-5b\transformer\diffusion_pytorch_model-00001-of-00002.safetensors which is required according to the checkpoint index.
```

**Comment by kijai** [comment]
> Thankyou again! Ok, so after another update/refresh cycle, I now have the custom nodes appearing correctly!
> 
> But attempting to queue the example workflows now gives errors:
> 
> If I select the 2b model, I get:
> 
> ```
> Error no file named diffusion_pytorch_model.bin found in directory C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\CogVideo\CogVideo2B.
> ```
> 
> Whereas if I select the 5b model instead:
> 
> ```
> ValueError: C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\CogVideo\CogVideoX-5b\transformer does not appear to have a file named C:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\CogVideo\CogVideoX-5b\transformer\diffusion_pytorch_model-00001-of-00002.safetensors which is required according to the checkpoint index.
> ```

It looks like the autodownload has failed, you can attempt it again by remove the model's folder, or manually download them from: https://huggingface.co/THUDM/CogVideoX-5b/tree/main

Manual download is bit of a pain as diffusers models have many files in many folders, basically everything but the text encoder are required.

**Comment by alastaira** [comment]
Ah, I deleted the models/CogVideo folder (which _looked_ like it was fully populated) and let it automatically redownload them, and it seems to have worked - thankyou!

**Comment by grokiki** [comment]
Updating diffusers worked fine here !
Thx a lot !

**Comment by kijai** [comment]
> I continue to have problems installing the cogvid nodes. When I restart after the failed import message in the manager the terminal shows repeated error messages mentioning something associated with the llm assistant nodes or other llm and llama nodes. For example:
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-llm-assistant\config.yaml
> 
> I've already been to the all the llm nodes folders and pulled the requirements which did not stop these errors.

LLM nodes have nothing to do with these nodes though, if these nodes won't load there should be something referring to `ComfyUI-CogVideoXWrapper` in the log.

**Comment by Wholebitmedia** [comment]
That seemed strange to me. I looked over this thread again after creating the venv and dowloading the diffusers and tried the 
python U diffusers install and got this error after seeing that all the requirements were already satisfied.

WARNING: Error parsing dependencies of torchsde: .* suffix can only be used with `==` or `!=` operators
    numpy (>=1.19.*) ; python_version >= "3.7"
           ~~~~~~~^
