### ISSUE TITLE
bad rendering if I lower the number of frames

### ISSUE THREAD

**Issue by rachidlamouchi** [kijai/ComfyUI-CogVideoXWrapper#78]
Hi, when I lower the number of frames I get this result :
![Capture d’écran 2024-09-21 005017](https://github.com/user-attachments/assets/7028a59b-a49b-4ac8-b86a-a8cdacee96a4)
cogvideox_I2V_example_01
RTX3090 24Gb

**Comment by kijai** [comment]
Yes, the I2V model only supports 49 frames, if you want to do shorter you can use the CogVideoX-Fun -versions.

**Comment by rachidlamouchi** [comment]
thanks for the answer, unfortunately the fun is not as good, I lower to 10 steps and I wait ^^
