### ISSUE TITLE
error trying to run GGUF model

### ISSUE THREAD

**Issue by FemBoxbrawl** [kijai/ComfyUI-CogVideoXWrapper#79]
![Screenshot 2024-09-21 015912](https://github.com/user-attachments/assets/508115d5-d3c7-40d0-a484-601d0eb36470)

![Screenshot 2024-09-21 020021](https://github.com/user-attachments/assets/e070af59-4acd-49d2-b0bf-2dc5bf3160b3)

do you have an example workflow for GGUF models?

**Comment by kijai** [comment]
Not yet, and there's no GGUF for the I2V model yet, which is why that setup fails. 

The CogVideoX-Fun -version has GGUF so you can use it's example workflow as base and replace the model loader there instead.
