### ISSUE TITLE
t5 model in the examples

### ISSUE THREAD

**Issue by dgg8411** [kijai/ComfyUI-CogVideoXWrapper#8]
how can I download the t5 model t5\\google_t5-v1_1-xxl_encoderonly-fp8_e4m3fn.safetensors？
And is it compatible with the “Clip Loader”？

**Comment by Aljnk** [comment]
https://huggingface.co/mcmonkey/google_t5-v1_1-xxl_encoderonly/tree/main

**Comment by dgg8411** [comment]
> https://huggingface.co/mcmonkey/google_t5-v1_1-xxl_encoderonly/tree/main

It worked, thank you

**Comment by pricenuclear** [comment]
where does one place the file ? CLIP folder ? thank you
