### ISSUE TITLE
Is it possible to reduce VRAM usage during VAE encode?

### ISSUE THREAD

**Issue by wailovet** [kijai/ComfyUI-CogVideoXWrapper#84]
When there is only 16G VRAM, an OOM error occurs in the VAE encoding stage when using a resolution of 1024.

**Comment by kijai** [comment]
Yes, use the tiled vae option. Smaller the tiles, less memory it uses.

**Comment by wailovet** [comment]
The current VAE encode seems not to implement the tiled vae option.

**Comment by kijai** [comment]
> The current VAE encode seems not to implement the tiled vae option.

Oh sorry I read it as decode... I actually tried enabling tiling for encoding but it didn't change anything, will need to investigate more. I'm barely able to fit 1024 with 24GB myself.

**Comment by wailovet** [comment]
I tried of https://github.com/MinusZoneAI/ComfyUI-CogVideoX-MZ/blob/main/mz_enable_vae_encode_tiling.py, but it still seems to run OOM when enable_sequential_cpu_offload is enabled. It would be even better if it could be implemented in ComfyUI-CogVideoXWrapper.
