### ISSUE TITLE
preview image possible?

### ISSUE THREAD

**Issue by zweifuchs** [kijai/ComfyUI-CogVideoXWrapper#90]
Hello,
I just wanted to ask if there is a possibility to get something like a preview image for the upcoming clip? It takes about 8mins for a clip to render on my 3090 and it would be nice to quit the process if the resulting video has a different look then what i have hoped for.  thanks for your time!

**Comment by kijai** [comment]
I don't think that's really feasible with video models, especially this one that uses 3D VAE , even if it was it would further slow it down. Maybe if someone figures a latent2rgb matrix for this or something like the tiny autoencoder(taesd).

Best you can do is just use less steps, and once you find a seed that gives you the motion you want, run it again with more steps.
