### ISSUE TITLE
ComfyUI-CogVideoXWrapper (Fix or Uninstall)

### ISSUE THREAD

**Issue by KeeeeperOfTheLight** [kijai/ComfyUI-CogVideoXWrapper#93]
hello guys.
i accidentally closed comyui cmd and it was downloading the cogvideo model and sence then CogVideoXWrapper not working anymore i tried to reinstall the wrapper with requirments and still the same issue.
i tried to reinstall comyui and still the same issue, oh and i installed timm too and still.

it was working fine on text to vid and img2vid i tried to download the newer version and this happened.

so please can someone help me.

![cogvideo2](https://github.com/user-attachments/assets/50c04b49-99e7-4b63-979b-72dec603a1fa)

![cogvideo3](https://github.com/user-attachments/assets/e2520d96-a80f-4a2a-8d37-ce806abaf00d)

![cogvideo](https://github.com/user-attachments/assets/531dd2d6-0c01-46e6-b271-f2dbe836b7f1)

**Comment by sbalani** [comment]
I'm having the exact same issue.

**Comment by kijai** [comment]
Looks like timm sneaked in as dependency with the PAB update, it's not actually used by CogVideoX anyway so I've now removed it as requirement, updating should solve that issue.

For any other import issues please always report what the error in the log says, like above with timm, it's very helpful.

**Comment by KeeeeperOfTheLight** [comment]
> Looks like timm sneaked in as dependency with the PAB update, it's not actually used by CogVideoX anyway so I've now removed it as requirement, updating should solve that issue.
> 
> For any other import issues please always report what the error in the log says, like above with timm, it's very helpful.

thank you so match i update all and it fixed. ❤️
