### ISSUE TITLE
Expected Weight size error? 

### ISSUE THREAD

**Issue by Duemellon** [kijai/ComfyUI-CogVideoXWrapper#94]
RuntimeError: Given groups=1, weight of size [3072, 16, 2, 2], expected input[26, 32, 60, 90] to have 16 channels, but got 32 channels instead

Anyone else getting this?

**Comment by kijai** [comment]
That looks like you are inputting an image (which turns the input to 32 channels) to a text2vid model (which only has 16 input channels).

**Comment by Duemellon** [comment]
how do I address this? I tried converting the image to RGB with a node. How can I change the channel count? 

i'm trying to follow a tutorial for i2v using CogVideo (GGUF  preferred)

**Comment by Duemellon** [comment]
this that tute:

https://www.youtube.com/watch?v=--sbejiJ858

**Comment by kijai** [comment]
> how do I address this? I tried converting the image to RGB with a node. How can I change the channel count?
> 
> i'm trying to follow a tutorial for i2v using CogVideo (GGUF preferred)

It's simply determined by the model you are using, the I2V model has 32 channels so you should have that selected, it sounds like you don't? If you do and it still errors out, please show me how the workflow is setup.

**Comment by Duemellon** [comment]
oh, just up the channels on the Cog Vid node.

**Comment by Duemellon** [comment]
I'm getting this error 
RuntimeError: Given groups=1, weight of size [3072, 16, 2, 2], expected input[26, 32, 60, 90] to have 16 channels, but got 32 channels instead

And these are my nodes. What fields should I be updating? I don't see one with a value of 26, 32, 60, 90 except the ImageEncode which I changed to 32 from 16 but the error didn't change any

![image](https://github.com/user-attachments/assets/33959495-5bf1-4ace-b315-0329da51823f)

**Comment by kijai** [comment]
> I'm getting this error 
> RuntimeError: Given groups=1, weight of size [3072, 16, 2, 2], expected input[26, 32, 60, 90] to have 16 channels, but got 32 channels instead
> 
> And these are my nodes. What fields should I be updating? I don't see one with a value of 26, 32, 60, 90 except the ImageEncode which I changed to 32 from 16 but the error didn't change any
> 
> ![image](https://github.com/user-attachments/assets/6bb7e23b-719b-45be-915a-a42d5a02e3b4)
> 
> 

What model do you have selected? It needs to be the I2V -model for that setup.

**Comment by Duemellon** [comment]
OK, so that makes progress. Wow. This is slow for me. I'll keep working at it.

Sorry for the earlier confusion. I used i2v as shorthand but didn't realize it was a specific model suffix named.

**Comment by Duemellon** [comment]
rtx 3060 12gb

**Comment by Duemellon** [comment]
well, it went to completion 
1 hr 45 min later
20 frames at 20 steps
Original image started with

I think I'm done with this for the while & I'll check back in a month or so. Seems like it's just out of reach for my computer (1hr 45?) and my familiarity. 

![image](https://github.com/user-attachments/assets/b1694df5-107e-464d-99a9-59a55bea9247)

Animation ended with
![image](https://github.com/user-attachments/assets/9d555f75-2600-4a53-9372-065ddd003d48)

**Comment by kijai** [comment]
The I2V model can only do 49 frames, results end up like that otherwise. If it took that long then your GPU doesn't have enough memory, you can try either using the GGUF version of the model, or the "fun" version (different workflow) which allows to use less frames and smaller resolution.

**Comment by Duemellon** [comment]
ok, no more mosaic & finally got a vid. Thanks for the good work on all this!
