### ISSUE TITLE
Low VRAM Workflow for IMG2VID GGUF?

### ISSUE THREAD

**Issue by FemBoxbrawl** [kijai/ComfyUI-CogVideoXWrapper#96]
I was wondering if it is possible to lower the resolution on regular CogvideoX img2vid sampling in some way to increase inference? 

I know CogvideoX fun works, but it does not give the greatest results compared to the regular i2v model. If it is not possible, I will just have to wait for my upgrade.. Then I will stick to CogvideoXfun at 320p for now.

**Comment by kijai** [comment]
Nope, it's locked to 49 frames at 720x480, just how the model is trained, nothing to be done about it currently.
