### ISSUE TITLE
1Torch was not compiled with flash attention

### ISSUE THREAD

**Issue by Vektor369** [kijai/ComfyUI-CogVideoXWrapper#97]
I know this most likely has nothing to do with Cog, but I'm getting the following:
```ComfyUI\comfy\ldm\modules\attention.py:407: UserWarning: 1Torch was not compiled with flash attention.```
It still runs okay, I'm just wondering if this is compromising my quality or speed or anything.

Thanks in advance for any help.

**Comment by kijai** [comment]
It's normal for Windows currently as flash_attn isn't supported by the prebuilt torch installs. CogVideoX itself doesn't benefit from it either, as far as I know.

**Comment by Vektor369** [comment]
Awesome! Thank you so much kijai!
