### ISSUE TITLE
[HELP] -  Any info related to PAB ?

### ISSUE THREAD

**Issue by NonaBuhtig** [kijai/ComfyUI-CogVideoXWrapper#98]
PAB has been added to the code, but I cannot find any relevant information about it. Can anyone give some useful hints about what is PAB is and how to use it?

Thanks :)

**Comment by kijai** [comment]
In short: it's a tradeoff of using more VRAM for faster sampling with very small quality loss.

https://oahzxl.github.io/PAB/

With single GPU we won't get such crazy speed increase as they advertise, but it can still be ~30-40% on some GPUs.

**Comment by NonaBuhtig** [comment]
Interesting ! Thank you !
 🥇
