### ISSUE TITLE
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

### ISSUE THREAD

**Issue by wmbassyouni** [kijai/ComfyUI-CogVideoXWrapper#99]
Error appears while running generation. I tried to research this error and found references about other models file not downloading correctly. But I made sure that they are and downloaded more than once time. Here are the current files in the transformer directory: 
![image](https://github.com/user-attachments/assets/8ad6318f-a5fa-4874-a0cb-6c7346c19d91)

**Comment by kijai** [comment]
That folder does look correct, but what about the others? The error suggests some file is corrupt, incomplete download or something like that.

**Comment by wmbassyouni** [comment]
I have repeatedly tried it. Deleting the model directory and then re-triggering its download using this workflow:

cogvideox_I2V_example_01.json which contains the model download node :
![image](https://github.com/user-attachments/assets/2d987d7a-a913-4db4-9d3e-eec86a2119a7)

The fuller error I am getting is: 

 File "C:\Software\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 406, in load_clip
    clip_data.append(comfy.utils.load_torch_file(p, safe_load=True))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Software\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 34, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Software\ComfyUI_windows_portable\python_embeded\Lib\site-packages\safetensors\torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer

Could there be a different way to download the model ?

**Comment by kijai** [comment]
Yes you can manually download from here, just have to make sure the folder structure and file names then match, almost everything but the text encoder folder and readmes etc. is required:

https://huggingface.co/THUDM/CogVideoX-5b-I2V/tree/main

**Comment by wmbassyouni** [comment]
thanks will try that.

**Comment by wmbassyouni** [comment]
After trying for a long time, decided to try out GGUF instead. It worked for the FUN model but since its not an I2V model, tried to switch to the GGUF I2V model but got an error on the sampler that it can only be used for the fun model. Is there a difference sampler that I can use for the CogVideoX_5b_I2V_GGUF_Q4_0 model ?

![image](https://github.com/user-attachments/assets/64ca8405-f066-4519-a45e-110f7cb86c23)

**Comment by wmbassyouni** [comment]
Should also mention that the CogVideoSampler suggested does not have an image input and so could not use it

![image](https://github.com/user-attachments/assets/6122849e-6815-48d4-8bf4-c7b7490a9aa4)

**Comment by kijai** [comment]
> After trying for a long time, decided to try out GGUF instead. It worked for the FUN model but since its not an I2V model, tried to switch to the GGUF I2V model but got an error on the sampler that it can only be used for the fun model. Is there a difference sampler that I can use for the CogVideoX_5b_I2V_GGUF_Q4_0 model ?
> 
> ![image](https://github.com/user-attachments/assets/64ca8405-f066-4519-a45e-110f7cb86c23)
> 

Yes it's different sampler, there's example workflow for it in the examples folder.
